### ISSUE TITLE
Provide documentation for classes used as parameters

### ISSUE THREAD

**Issue by thagomizer** [GoogleCloudPlatform/google-cloud-ruby#1473] opened 2017-05-16 15:46 UTC
In monitoring when I call MetricServiceClient#list_time_series I can provide an interval and a view.

Interval is Google::Monitoring::V3::TimeInterval
and view is a Google::Monitoring::V3::ListTimeSeriesRequest::TimeSeriesView. The types weren't linked in the docs and there are no docs for TimeSeriesView at all. 

Can we link the classes in the docs and ensure that every class that may be used as a method arg has docs?

**Comment by geigerj** [comment] 2017-05-31 17:56
Filed https://github.com/googleapis/toolkit/issues/1312 as feature request for linking.

**Comment by geigerj** [comment] 2017-08-07 17:23
Closing, as duplicate of googleapis/toolkit#1312 (where the actual implementation was done). GAPIC generator changes will show up in the docs on the next GAPIC refresh.

**Closed by geigerj** 2017-08-07 17:23 UTC
Labels: API: monitoring, docs, gapic
