### ISSUE TITLE
Unable to use ADC with Video Intelligence client library

### ISSUE THREAD

**Issue by frankyn** [GoogleCloudPlatform/google-cloud-ruby#1891] opened 2017-12-20 01:23 UTC
Hi all,

I'm currently testing Ruby 2.5.0-rc1 with [ruby-docs-samples](https://github.com/GoogleCloudPlatform/ruby-docs-samples). I found an issue with the Video Intelligence samples where I'm unable to use ADC provided by the Cloud SDK. However, I'm able to use the NLP client library with ADC credentials. ~~Although, changing the Ruby version to 2.4.2 the similar issue is not raised.~~ More info, this issue is not present in the NLP client library. 

Exact error:
```
GaxError Exception occurred in retry method that was not classified as transient, caused by 7:Cloud Video Intelligence API has not been used in project usable-auth-library before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/videointelligence.googleapis.com/overview?project=usable-auth-library then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
```

**Comment by geigerj** [comment] 2017-12-20 04:04
It's unexpected for ADC provided by the Cloud SDK -- that is, ADC as provided by the `gcloud auth application-default login` command -- to work with Video Intelligence at all, including in other versions of Ruby. ADC is supported with a service key. I'd like to drill into this a bit more before we classify it as a bug.

**Comment by frankyn** [comment] 2017-12-20 04:33
Version is not an issue, I didn't `unset` the `GOOGLE_APPLICATION_CREDENTIALS` after switching to Ruby 2.4.2. My mistake, and I have updated the description of this issue to follow-up with the NLP client library successfully using ADC (made sure to unset the variable this time). 

Thanks Jacob.

**Comment by geigerj** [comment] 2017-12-20 17:01
@vchudnov-g Which APIs work with `gcloud auth application-default login` and which don't? Is there a list documented somewhere?

**Comment by blowmage** [comment] 2017-12-20 18:51
AFAIK all google-cloud gems should work with the gcloud CLI authentication. I believe the issue here is that the grpc gem is not compatible with Ruby 2.5. I have tested on both OS X and Linux and have not been able to get the grpc gem to work on Ruby 2.5.0-rc1.

I don't know why you are getting that specific error message, but I suspect it has more to do with the Ruby 2.5 support than recognizing the gcloud CLI authentication.

**Comment by geigerj** [comment] 2017-12-20 18:58
@blowmage Video Intelligence doesn't work with `gcloud auth application-default login`. This is known and is intended behavior. @vchudnov-g is our lead for auth and should be able to clarify in which cases `gcloud auth application-default login` should work.

**Comment by frankyn** [comment] 2017-12-20 18:59
@blowmage I compiled the gRPC gem using Ruby 2.5.0-rc1. This issue also occurs using Ruby 2.4.2, but I made a mistake thinking ADC worked with Video Intelligence using this version.

**Comment by frankyn** [comment] 2017-12-20 20:33
Sat with @blowmage debugging this issue and found it to be a service side issue with the API not being enabled for the `usable-auth-library` project. @geigerj also confirmed this and we are hoping to understanding the state of the auth world from @vchudnov-g :smile:

**Comment by blowmage** [comment] 2018-01-08 18:54
@geigerj Can you give us an update?

**Comment by vchudnov-g** [comment] 2018-01-08 20:20
Apologies for the delay in replying.

The error message quoted above includes the critical part `API has not been used in project usable-auth-library`. This is the Google-owned Cloud Console project that allows `gcloud auth application-default login` to work with a given API. We are actively discouraging the use of this mechanism, particularly for new APIs. The recommended way of using Application Default Credentials is to download a service account file and then set the `GOOGLE_APPLICATION_CREDENTIALS` environment variable to point to it. We're in the process of updating our docs; for example, see https://cloud.google.com/docs/authentication/production

Please let me know whether this helps.

**Comment by frankyn** [comment] 2018-01-10 20:56
@vchudnov-g is it possible to update this error message to redirect users to using a service account? The message is very confusing without this additional context.

**Comment by vchudnov-g** [comment] 2018-01-11 18:29
I agree that a better error message would be very helpful. We're working on this internally.

**Comment by frankyn** [comment] 2018-01-11 18:59
Thanks @vchudnov-g!

**Comment by geigerj** [comment] 2018-01-17 17:44
Closing this question. Thanks for the clarification, @vchudnov-g.

**Closed by geigerj** 2018-01-17 17:44 UTC
Labels: api: video intelligence, auth, type: question
