### ISSUE TITLE
`gem install google-cloud` fails with dependency on google-cloud-error_reporting

### ISSUE THREAD

**Issue by remi** [GoogleCloudPlatform/google-cloud-ruby#1033] opened 2016-11-09 00:02 UTC
If I `gem install google-cloud` as shown in the [quickstart](https://github.com/GoogleCloudPlatform/google-cloud-ruby#quick-start), I get a failure:

```
$ gem install google-cloud
Fetching: google-cloud-core-0.21.0.gem (100%)
Successfully installed google-cloud-core-0.21.0
Fetching: uber-0.0.15.gem (100%)
Successfully installed uber-0.0.15
Fetching: representable-2.3.0.gem (100%)
Successfully installed representable-2.3.0
Fetching: retriable-2.1.0.gem (100%)
Successfully installed retriable-2.1.0
Fetching: hurley-0.2.gem (100%)
Successfully installed hurley-0.2
Fetching: httpclient-2.8.2.4.gem (100%)
Successfully installed httpclient-2.8.2.4
Fetching: google-api-client-0.9.20.gem (100%)
Successfully installed google-api-client-0.9.20
Fetching: google-cloud-bigquery-0.21.0.gem (100%)
Successfully installed google-cloud-bigquery-0.21.0
Fetching: google-protobuf-3.0.2-universal-darwin.gem (100%)
Successfully installed google-protobuf-3.0.2-universal-darwin
Fetching: grpc-1.0.1-universal-darwin.gem (100%)
Successfully installed grpc-1.0.1-universal-darwin
Fetching: googleapis-common-protos-1.3.4.gem (100%)
Successfully installed googleapis-common-protos-1.3.4
Fetching: rly-0.2.3.gem (100%)
Successfully installed rly-0.2.3
Fetching: google-gax-0.6.0.gem (100%)
Successfully installed google-gax-0.6.0
Fetching: google-cloud-datastore-0.21.0.gem (100%)
Successfully installed google-cloud-datastore-0.21.0
Fetching: google-cloud-dns-0.21.0.gem (100%)
Successfully installed google-cloud-dns-0.21.0
Fetching: google-cloud-language-0.21.0.gem (100%)
Successfully installed google-cloud-language-0.21.0
Fetching: orderedhash-0.0.6.gem (100%)
Successfully installed orderedhash-0.0.6
Fetching: google-cloud-logging-0.21.1.gem (100%)
Successfully installed google-cloud-logging-0.21.1
Fetching: google-cloud-monitoring-0.21.0.gem (100%)
Successfully installed google-cloud-monitoring-0.21.0
Fetching: grpc-google-iam-v1-0.6.8.gem (100%)
Successfully installed grpc-google-iam-v1-0.6.8
Fetching: google-cloud-pubsub-0.21.0.gem (100%)
Successfully installed google-cloud-pubsub-0.21.0
Fetching: google-cloud-resource_manager-0.21.0.gem (100%)
Successfully installed google-cloud-resource_manager-0.21.0
Fetching: google-cloud-speech-0.21.0.gem (100%)
Successfully installed google-cloud-speech-0.21.0
Fetching: google-cloud-storage-0.21.0.gem (100%)
Successfully installed google-cloud-storage-0.21.0
Fetching: google-cloud-translate-0.21.0.gem (100%)
Successfully installed google-cloud-translate-0.21.0
Fetching: google-cloud-vision-0.21.1.gem (100%)
Successfully installed google-cloud-vision-0.21.1
Fetching: google-cloud-0.21.0.gem (100%)
ERROR:  Error installing google-cloud:
	google-cloud requires google-cloud-error_reporting (~> 0.21.0)
```

**Comment by blowmage** [comment] 2016-11-09 06:50
I've got a repo, when installing 0.20.0:

```
☣ [gcloud-ruby:gcloud-0.20] $ gem install google-cloud -v 0.20.0
Fetching: google-cloud-core-0.20.1.gem (100%)
Successfully installed google-cloud-core-0.20.1
Fetching: uber-0.0.15.gem (100%)
Successfully installed uber-0.0.15
Fetching: representable-2.3.0.gem (100%)
Successfully installed representable-2.3.0
Fetching: retriable-2.1.0.gem (100%)
Successfully installed retriable-2.1.0
Fetching: mime-types-data-3.2016.0521.gem (100%)
Successfully installed mime-types-data-3.2016.0521
Fetching: mime-types-3.1.gem (100%)
Successfully installed mime-types-3.1
Fetching: hurley-0.2.gem (100%)
Successfully installed hurley-0.2
Fetching: little-plugger-1.1.4.gem (100%)
Successfully installed little-plugger-1.1.4
Fetching: logging-2.1.0.gem (100%)
Successfully installed logging-2.1.0
Fetching: memoist-0.15.0.gem (100%)
Successfully installed memoist-0.15.0
Fetching: os-0.9.6.gem (100%)
Successfully installed os-0.9.6
Fetching: signet-0.7.3.gem (100%)
Successfully installed signet-0.7.3
Fetching: googleauth-0.5.1.gem (100%)
Successfully installed googleauth-0.5.1
Fetching: httpclient-2.8.2.4.gem (100%)
Successfully installed httpclient-2.8.2.4
Fetching: google-api-client-0.9.20.gem (100%)
Successfully installed google-api-client-0.9.20
Fetching: google-cloud-bigquery-0.20.2.gem (100%)
Successfully installed google-cloud-bigquery-0.20.2
Fetching: google-protobuf-3.0.2-universal-darwin.gem (100%)
Successfully installed google-protobuf-3.0.2-universal-darwin
Fetching: grpc-1.0.1-universal-darwin.gem (100%)
Successfully installed grpc-1.0.1-universal-darwin
Fetching: googleapis-common-protos-1.3.4.gem (100%)
Successfully installed googleapis-common-protos-1.3.4
Fetching: google-cloud-datastore-0.20.1.gem (100%)
Successfully installed google-cloud-datastore-0.20.1
Fetching: zonefile-1.04.gem (100%)
Successfully installed zonefile-1.04
Fetching: google-cloud-dns-0.20.1.gem (100%)
Successfully installed google-cloud-dns-0.20.1
Fetching: rly-0.2.3.gem (100%)
Successfully installed rly-0.2.3
Fetching: google-gax-0.4.4.gem (100%)
Successfully installed google-gax-0.4.4
Fetching: google-cloud-language-0.20.2.gem (100%)
Successfully installed google-cloud-language-0.20.2
Fetching: google-cloud-logging-0.20.1.gem (100%)
Successfully installed google-cloud-logging-0.20.1
Fetching: google-cloud-pubsub-0.20.1.gem (100%)
Successfully installed google-cloud-pubsub-0.20.1
Fetching: google-cloud-resource_manager-0.20.1.gem (100%)
Successfully installed google-cloud-resource_manager-0.20.1
Fetching: google-cloud-storage-0.20.2.gem (100%)
Successfully installed google-cloud-storage-0.20.2
Fetching: google-cloud-translate-0.20.1.gem (100%)
Successfully installed google-cloud-translate-0.20.1
Fetching: google-cloud-vision-0.20.2.gem (100%)
Successfully installed google-cloud-vision-0.20.2
Fetching: google-cloud-0.20.0.gem (100%)
Successfully installed google-cloud-0.20.0
32 gems installed
```

But when installing 0.21.0:

```
☣ [gcloud-ruby:gcloud-0.21] $ gem install google-cloud -v 0.21.0
Fetching: google-cloud-core-0.21.0.gem (100%)
Successfully installed google-cloud-core-0.21.0
Fetching: uber-0.0.15.gem (100%)
Successfully installed uber-0.0.15
Fetching: representable-2.3.0.gem (100%)
Successfully installed representable-2.3.0
Fetching: retriable-2.1.0.gem (100%)
Successfully installed retriable-2.1.0
Fetching: mime-types-data-3.2016.0521.gem (100%)
Successfully installed mime-types-data-3.2016.0521
Fetching: mime-types-3.1.gem (100%)
Successfully installed mime-types-3.1
Fetching: hurley-0.2.gem (100%)
Successfully installed hurley-0.2
Fetching: little-plugger-1.1.4.gem (100%)
Successfully installed little-plugger-1.1.4
Fetching: logging-2.1.0.gem (100%)
Successfully installed logging-2.1.0
Fetching: memoist-0.15.0.gem (100%)
Successfully installed memoist-0.15.0
Fetching: os-0.9.6.gem (100%)
Successfully installed os-0.9.6
Fetching: signet-0.7.3.gem (100%)
Successfully installed signet-0.7.3
Fetching: googleauth-0.5.1.gem (100%)
Successfully installed googleauth-0.5.1
Fetching: httpclient-2.8.2.4.gem (100%)
Successfully installed httpclient-2.8.2.4
Fetching: google-api-client-0.9.20.gem (100%)
Successfully installed google-api-client-0.9.20
Fetching: google-cloud-bigquery-0.21.0.gem (100%)
Successfully installed google-cloud-bigquery-0.21.0
Fetching: google-protobuf-3.0.2-universal-darwin.gem (100%)
Successfully installed google-protobuf-3.0.2-universal-darwin
Fetching: grpc-1.0.1-universal-darwin.gem (100%)
Successfully installed grpc-1.0.1-universal-darwin
Fetching: googleapis-common-protos-1.3.4.gem (100%)
Successfully installed googleapis-common-protos-1.3.4
Fetching: rly-0.2.3.gem (100%)
Successfully installed rly-0.2.3
Fetching: google-gax-0.6.0.gem (100%)
Successfully installed google-gax-0.6.0
Fetching: google-cloud-datastore-0.21.0.gem (100%)
Successfully installed google-cloud-datastore-0.21.0
Fetching: zonefile-1.04.gem (100%)
Successfully installed zonefile-1.04
Fetching: google-cloud-dns-0.21.0.gem (100%)
Successfully installed google-cloud-dns-0.21.0
Fetching: google-cloud-language-0.21.0.gem (100%)
Successfully installed google-cloud-language-0.21.0
Fetching: orderedhash-0.0.6.gem (100%)
Successfully installed orderedhash-0.0.6
Fetching: google-cloud-logging-0.21.1.gem (100%)
Successfully installed google-cloud-logging-0.21.1
Fetching: google-cloud-monitoring-0.21.0.gem (100%)
Successfully installed google-cloud-monitoring-0.21.0
Fetching: grpc-google-iam-v1-0.6.8.gem (100%)
Successfully installed grpc-google-iam-v1-0.6.8
Fetching: google-cloud-pubsub-0.21.0.gem (100%)
Successfully installed google-cloud-pubsub-0.21.0
Fetching: google-cloud-resource_manager-0.21.0.gem (100%)
Successfully installed google-cloud-resource_manager-0.21.0
Fetching: google-cloud-speech-0.21.0.gem (100%)
Successfully installed google-cloud-speech-0.21.0
Fetching: google-cloud-storage-0.21.0.gem (100%)
Successfully installed google-cloud-storage-0.21.0
Fetching: google-cloud-translate-0.21.0.gem (100%)
Successfully installed google-cloud-translate-0.21.0
Fetching: google-cloud-vision-0.21.1.gem (100%)
Successfully installed google-cloud-vision-0.21.1
Fetching: google-cloud-0.21.0.gem (100%)
ERROR:  Error installing google-cloud:
	google-cloud requires google-cloud-error_reporting (~> 0.21.0)
☣ [gcloud-ruby:gcloud-0.21] $ gem install google-cloud-error_reporting -v "~> 0.21.0"
Fetching: google-cloud-error_reporting-0.21.2.gem (100%)
Successfully installed google-cloud-error_reporting-0.21.2
1 gem installed
☣ [gcloud-ruby:gcloud-0.21] $ gem install google-cloud -v 0.21.0
Successfully installed google-cloud-0.21.0
1 gem installed
```

I've inspected the google-cloud and google-cloud-error_reporting gems, and their registration on rubygems.org, and everything looks to be correct. I don't see a reason for why the install is behaving this way.

**Comment by blowmage** [comment] 2016-11-09 07:02
When using bundler and switching the dependency from 0.20.0 to 0.21.0 in the Gemfile I get the following error:

```
☣ [tmp:google-cloud-0.20] $ bundle update
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Resolving dependencies...
Bundler could not find compatible versions for gem "google-cloud-error_reporting":
  In Gemfile:
    google-cloud (= 0.21.0) was resolved to 0.21.0, which depends on
      google-cloud-error_reporting (~> 0.21.0)

Could not find gem 'google-cloud-error_reporting (~> 0.21.0)', which is required by gem 'google-cloud (= 0.21.0)', in any of
the sources.
```

I don't understand where this behavior is coming from. The gem is available on rubygems. I suspect a bug in rubygems or the rubygems API, but I'm not sure where.

**Comment by blowmage** [comment] 2016-11-09 16:01
So, near as I can tell, there is a bug in the rubygems API that is causing this.

If you look at the gem as it is defined on the rubygems API, the dependency on `google-cloud-error_reporting` is listed: https://rubygems.org/api/v1/gems/google-cloud.json

```javascript
{
  "name": "google-cloud",
  "downloads": 7658,
  "version": "0.21.0",
  "version_downloads": 547,
  "platform": "ruby",
  "authors": "Mike Moore, Chris Smith",
  "info": "google-cloud is the official library for Google Cloud Platform APIs.",
  "licenses": ["Apache-2.0"],
  "metadata": {},
  "sha": "31f532a1f425da6ab6bda43985172daced665f3262d528ff5631f2d3f3cc0700",
  "project_uri": "https://rubygems.org/gems/google-cloud",
  "gem_uri": "https://rubygems.org/gems/google-cloud-0.21.0.gem",
  "homepage_uri": "http://googlecloudplatform.github.io/google-cloud-ruby/",
  "wiki_uri": null,
  "documentation_uri": "http://www.rubydoc.info/gems/google-cloud/0.21.0",
  "mailing_list_uri": null,
  "source_code_uri": null,
  "bug_tracker_uri": null,
  "dependencies": {
    "development": [{
      "name": "actionpack",
      "requirements": "~\u003e 4.0"
    }, {
      "name": "autotest-suffix",
      "requirements": "~\u003e 1.1"
    }, {
      "name": "minitest",
      "requirements": "~\u003e 5.9"
    }, {
      "name": "minitest-autotest",
      "requirements": "~\u003e 1.0"
    }, {
      "name": "minitest-focus",
      "requirements": "~\u003e 1.1"
    }, {
      "name": "minitest-rg",
      "requirements": "~\u003e 5.2"
    }, {
      "name": "rack",
      "requirements": "\u003e= 0.1"
    }, {
      "name": "railties",
      "requirements": "~\u003e 4.0"
    }, {
      "name": "rubocop",
      "requirements": "\u003c= 0.35.1"
    }, {
      "name": "simplecov",
      "requirements": "~\u003e 0.9"
    }, {
      "name": "yard",
      "requirements": "~\u003e 0.9"
    }, {
      "name": "yard-doctest",
      "requirements": "~\u003e 0.1.6"
    }],
    "runtime": [{
      "name": "google-cloud-bigquery",
      "requirements": "~\u003e 0.21.0"
    }, {
      "name": "google-cloud-datastore",
      "requirements": "~\u003e 0.21.0"
    }, {
      "name": "google-cloud-dns",
      "requirements": "~\u003e 0.21.0"
    }, {
      "name": "google-cloud-error_reporting",
      "requirements": "~\u003e 0.21.0"
    }, {
      "name": "google-cloud-language",
      "requirements": "~\u003e 0.21.0"
    }, {
      "name": "google-cloud-logging",
      "requirements": "~\u003e 0.21.0"
    }, {
      "name": "google-cloud-monitoring",
      "requirements": "~\u003e 0.21.0"
    }, {
      "name": "google-cloud-pubsub",
      "requirements": "~\u003e 0.21.0"
    }, {
      "name": "google-cloud-resource_manager",
      "requirements": "~\u003e 0.21.0"
    }, {
      "name": "google-cloud-speech",
      "requirements": "~\u003e 0.21.0"
    }, {
      "name": "google-cloud-storage",
      "requirements": "~\u003e 0.21.0"
    }, {
      "name": "google-cloud-translate",
      "requirements": "~\u003e 0.21.0"
    }, {
      "name": "google-cloud-vision",
      "requirements": "~\u003e 0.21.0"
    }]
  }
}
```

But, the rubygems CLI makes a different API call when installing, and this API does not list the `google-cloud-error_reoporting` dependency: https://api.rubygems.org/api/v1/dependencies.json?gems=google-cloud

```javascript
[{
  "name": "google-cloud",
  "number": "0.20.1",
  "platform": "ruby",
  "dependencies": [
    ["google-cloud-vision", "~\u003e 0.20.0"],
    ["google-cloud-translate", "~\u003e 0.20.0"],
    ["google-cloud-storage", "~\u003e 0.20.0"],
    ["google-cloud-speech", "~\u003e 0.20.0"],
    ["google-cloud-resource_manager", "~\u003e 0.20.0"],
    ["google-cloud-pubsub", "~\u003e 0.20.0"],
    ["google-cloud-logging", "~\u003e 0.20.0"],
    ["google-cloud-language", "~\u003e 0.20.0"],
    ["google-cloud-dns", "~\u003e 0.20.0"],
    ["google-cloud-datastore", "~\u003e 0.20.0"],
    ["google-cloud-bigquery", "~\u003e 0.20.0"]
  ]
}, {
  "name": "google-cloud",
  "number": "0.21.0",
  "platform": "ruby",
  "dependencies": [
    ["google-cloud-vision", "~\u003e 0.21.0"],
    ["google-cloud-translate", "~\u003e 0.21.0"],
    ["google-cloud-storage", "~\u003e 0.21.0"],
    ["google-cloud-speech", "~\u003e 0.21.0"],
    ["google-cloud-resource_manager", "~\u003e 0.21.0"],
    ["google-cloud-pubsub", "~\u003e 0.21.0"],
    ["google-cloud-monitoring", "~\u003e 0.21.0"],
    ["google-cloud-logging", "~\u003e 0.21.0"],
    ["google-cloud-language", "~\u003e 0.21.0"],
    ["google-cloud-dns", "~\u003e 0.21.0"],
    ["google-cloud-datastore", "~\u003e 0.21.0"],
    ["google-cloud-bigquery", "~\u003e 0.21.0"]
  ]
}, {
  "name": "google-cloud",
  "number": "0.20.0",
  "platform": "ruby",
  "dependencies": [
    ["google-cloud-vision", "~\u003e 0.20.0"],
    ["google-cloud-translate", "~\u003e 0.20.0"],
    ["google-cloud-storage", "~\u003e 0.20.0"],
    ["google-cloud-resource_manager", "~\u003e 0.20.0"],
    ["google-cloud-pubsub", "~\u003e 0.20.0"],
    ["google-cloud-logging", "~\u003e 0.20.0"],
    ["google-cloud-language", "~\u003e 0.20.0"],
    ["google-cloud-dns", "~\u003e 0.20.0"],
    ["google-cloud-datastore", "~\u003e 0.20.0"],
    ["google-cloud-bigquery", "~\u003e 0.20.0"]
  ]
}]
```

I can't figure out where to report this, so I'm following up with some folks on the rubygems core team to figure out how to correct this.

**Comment by hxiong388** [comment] 2016-11-09 19:05
I spent almost two hours yesterday diagnosing this bug. I read like 10 posts on the topic of gem dependencies, and still can't figure out why this is happening.

**Comment by blowmage** [comment] 2016-11-09 19:36
I'm convinced this is a problem in the rubygems API. Something is caching an incomplete set of dependencies.

**Comment by blowmage** [comment] 2016-11-09 20:51
We've fixed this. The root cause was that the rubygems API was showing incomplete dependencies for the `google-cloud` 0.21.0 gem. I think the dependencies were cached and there is no way to flush or rebuild the cache. So we released `google-cloud` 0.21.1 and that has fixed the dependency data for 0.21.0.

More info here: rubygems/rubygems.org#1489

**Comment by quartzmo** [comment] 2016-11-09 21:26
Nice job @blowmage. It was impressive to pair with you on this and see you dig into the rubygems API and diagnose the issue. I assume you are waiting for @remi to verify, and close this issue?

**Comment by blowmage** [comment] 2016-11-09 23:19
Yeah, if we can get confirmation that it works now then it can be closed.

**Comment by hxiong388** [comment] 2016-11-09 23:25
It's now working for me:
```sh
hexiong@hexiong-linuxworkstation:~$ gem list google-cloud --no-version | xargs gem uninstall
Successfully uninstalled google-cloud-vision-0.21.1
Successfully uninstalled google-cloud-translate-0.21.0
Successfully uninstalled google-cloud-storage-0.21.0
Successfully uninstalled google-cloud-speech-0.21.0
Successfully uninstalled google-cloud-resource_manager-0.21.0
Successfully uninstalled google-cloud-pubsub-0.21.0
Successfully uninstalled google-cloud-monitoring-0.21.0
Successfully uninstalled google-cloud-logging-0.21.1
Successfully uninstalled google-cloud-language-0.21.0
Successfully uninstalled google-cloud-dns-0.21.0
Successfully uninstalled google-cloud-datastore-0.21.0
Successfully uninstalled google-cloud-bigquery-0.21.0
Successfully uninstalled google-cloud-core-0.21.0

hexiong@hexiong-linuxworkstation:~$ gem install google-cloud
Fetching: google-cloud-core-0.21.0.gem (100%)
Successfully installed google-cloud-core-0.21.0
Fetching: google-cloud-bigquery-0.21.0.gem (100%)
Successfully installed google-cloud-bigquery-0.21.0
Fetching: google-cloud-datastore-0.21.0.gem (100%)
Successfully installed google-cloud-datastore-0.21.0
Fetching: google-cloud-dns-0.21.0.gem (100%)
Successfully installed google-cloud-dns-0.21.0
Fetching: google-cloud-error_reporting-0.21.2.gem (100%)
Successfully installed google-cloud-error_reporting-0.21.2
Fetching: google-cloud-language-0.21.0.gem (100%)
Successfully installed google-cloud-language-0.21.0
Fetching: google-cloud-logging-0.21.1.gem (100%)
Successfully installed google-cloud-logging-0.21.1
Fetching: google-cloud-monitoring-0.21.0.gem (100%)
Successfully installed google-cloud-monitoring-0.21.0
Fetching: google-cloud-pubsub-0.21.0.gem (100%)
Successfully installed google-cloud-pubsub-0.21.0
Fetching: google-cloud-resource_manager-0.21.0.gem (100%)
Successfully installed google-cloud-resource_manager-0.21.0
Fetching: google-cloud-speech-0.21.0.gem (100%)
Successfully installed google-cloud-speech-0.21.0
Fetching: google-cloud-storage-0.21.0.gem (100%)
Successfully installed google-cloud-storage-0.21.0
Fetching: google-cloud-translate-0.21.0.gem (100%)
Successfully installed google-cloud-translate-0.21.0
Fetching: google-cloud-vision-0.21.1.gem (100%)
Successfully installed google-cloud-vision-0.21.1
Fetching: google-cloud-0.21.1.gem (100%)
Successfully installed google-cloud-0.21.1
Parsing documentation for google-cloud-core-0.21.0
Installing ri documentation for google-cloud-core-0.21.0
Parsing documentation for google-cloud-bigquery-0.21.0
Installing ri documentation for google-cloud-bigquery-0.21.0
Parsing documentation for google-cloud-datastore-0.21.0
Installing ri documentation for google-cloud-datastore-0.21.0
Parsing documentation for google-cloud-dns-0.21.0
Installing ri documentation for google-cloud-dns-0.21.0
Parsing documentation for google-cloud-error_reporting-0.21.2
Installing ri documentation for google-cloud-error_reporting-0.21.2
Parsing documentation for google-cloud-language-0.21.0
Installing ri documentation for google-cloud-language-0.21.0
Parsing documentation for google-cloud-logging-0.21.1
Installing ri documentation for google-cloud-logging-0.21.1
Parsing documentation for google-cloud-monitoring-0.21.0
Installing ri documentation for google-cloud-monitoring-0.21.0
Parsing documentation for google-cloud-pubsub-0.21.0
Installing ri documentation for google-cloud-pubsub-0.21.0
Parsing documentation for google-cloud-resource_manager-0.21.0
Installing ri documentation for google-cloud-resource_manager-0.21.0
Parsing documentation for google-cloud-speech-0.21.0
Installing ri documentation for google-cloud-speech-0.21.0
Parsing documentation for google-cloud-storage-0.21.0
Installing ri documentation for google-cloud-storage-0.21.0
Parsing documentation for google-cloud-translate-0.21.0
Installing ri documentation for google-cloud-translate-0.21.0
Parsing documentation for google-cloud-vision-0.21.1
Installing ri documentation for google-cloud-vision-0.21.1
Parsing documentation for google-cloud-0.21.1
Installing ri documentation for google-cloud-0.21.1
Done installing documentation for google-cloud-core, google-cloud-bigquery, google-cloud-datastore, google-cloud-dns, google-cloud-error_reporting, google-cloud-language, google-cloud-logging, google-cloud-monitoring, google-cloud-pubsub, google-cloud-resource_manager, google-cloud-speech, google-cloud-storage, google-cloud-translate, google-cloud-vision, google-cloud after 5 seconds
15 gems installed

```

**Comment by quartzmo** [comment] 2016-11-10 17:24
@remi Can we close this?

**Comment by blowmage** [comment] 2016-11-10 18:56
We have confirmation #1032 is fixed, so Imma close it. Please reopen if this is still an issue.

**Closed by blowmage** 2016-11-10 18:56 UTC
Labels: bug, error reporting, packaging

**Comment by palladius** [comment] 2017-04-02 11:18
I have a very similar issue with the same gem (!!). Trying to install Google's  GoogleCloudPlatform.getting-started-ruby/2-cloud-datastore/ and looking at this documentation: https://cloud.google.com/ruby/getting-started/using-cloud-datastore#installing_dependencies

$ bundle install
<all good>
$ rails server
/var/lib/gems/2.3.0/gems/google-cloud-error_reporting-0.21.2/lib/google/cloud/error_reporting/v1beta1/error_group_service_api.rb:28:in `require': cannot load such file -- google/gax (LoadError)
	from /var/lib/gems/2.3.0/gems/google-cloud-error_reporting-0.21.2/lib/google/cloud/error_reporting/v1beta1/error_group_service_api.rb:28:in `<top (required)>'
	from /var/lib/gems/2.3.0/gems/google-cloud-error_reporting-0.21.2/lib/google/cloud/error_reporting/v1beta1.rb:17:in `require'
	from /var/lib/gems/2.3.0/gems/google-cloud-error_reporting-0.21.2/lib/google/cloud/error_reporting/v1beta1.rb:17:in `<top (required)>'
	from /var/lib/gems/2.3.0/gems/google-cloud-0.22.0/lib/google-cloud.rb:41:in `require'
	from /var/lib/gems/2.3.0/gems/google-cloud-0.22.0/lib/google-cloud.rb:41:in `<top (required)>'
	from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:77:in `require'
	from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:77:in `block (2 levels) in require'
	from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:72:in `each'
	from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:72:in `block in require'
	from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:61:in `each'
	from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:61:in `require'
	from /usr/lib/ruby/vendor_ruby/bundler.rb:99:in `require'
	from /home/riccardo/git/gae-debiti/vendor/GoogleCloudPlatform.getting-started-ruby/2-cloud-datastore/config/application.rb:26:in `<top (required)>'
	from /var/lib/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:78:in `require'
	from /var/lib/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:78:in `block in server'
	from /var/lib/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:75:in `tap'
	from /var/lib/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:75:in `server'
	from /var/lib/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /var/lib/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:18:in `require'
	from bin/rails:18:in `<main>'

I've tried to uninstall that version of the gem as I have newer ones (0.23.3, 0.24.0), but apparently 
google-cloud-0.22.0 depends on google-cloud-error_reporting (~> 0.21.0)

so I'm stuck on this library
