### ISSUE TITLE
Partial Success with Status Details

### ISSUE THREAD

**Issue by qingling128** [GoogleCloudPlatform/google-cloud-ruby#1239] opened 2017-02-16 16:22 UTC
We are writing log entries to Logging API using the `write_log_entries` [method](
https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-logging/lib/google/cloud/logging/v2/logging_service_v2_client.rb#L308), and we enabled `partial_success`.

When a request has a mix of failed and successful entries, it raised a `GRPC::BadStatus` error. However, we can't find a way to get the status details to locate which entries are the failing ones.

To clarify it a bit, we are looking for something equivalent to the `WriteLogEntriesPartialErrors` mentioned in the documention of `partialSuccess` [here](https://cloud.google.com/logging/docs/reference/v2/rest/v2/entries/write).

Is this not supported yet?

**Comment by blowmage** [comment] 2017-02-16 17:36
Hi @qingling128, the [`GRPC::BadStatus`](http://www.rubydoc.info/gems/grpc/GRPC/BadStatus) object has a [`metadata`](http://www.rubydoc.info/gems/grpc/GRPC/BadStatus#metadata-instance_method) attribute. This is usually a hash, and I would expect it to include the detail you are looking for.

**Comment by qingling128** [comment] 2017-02-16 18:13
Hi @blowmage, thanks for taking a look. Yeah, I thought that too, and it was indeed a hash, but i got an empty hash instead.

The sample request I used (with unrelated fields replaced with "...") have three log entries. The first two should fail for invalid character ":" in the log names.
```
2017-02-16 18:00:50 +0000 [info]: 
[
	<Google::Logging::V2::LogEntry: proto_payload: nil, text_payload: "testing partial success", insert_id: "", json_payload: nil, http_request: nil, resource: ..., timestamp: ..., severity: :DEFAULT, labels: {"compute.googleapis.com/resource_name"=>...}, log_name: "projects/test-project/logs/aa:bb", operation: nil>,
	<Google::Logging::V2::LogEntry: proto_payload: nil, text_payload: "testing partial success", insert_id: "", json_payload: nil, http_request: nil, resource: ..., timestamp: ..., severity: :DEFAULT, labels: {"compute.googleapis.com/resource_name"=>...}, log_name: "projects/test-project/logs/aa:bb", operation: nil>,
	<Google::Logging::V2::LogEntry: proto_payload: nil, text_payload: "testing partial success", insert_id: "", json_payload: nil, http_request: nil, resource: ..., timestamp: ..., severity: :DEFAULT, labels: {"compute.googleapis.com/resource_name"=>...}, log_name: "", operation: nil>
]
```

And the error I got is:

```
2017-02-16 18:00:50 +0000 [info]: error =
#<GRPC::BadStatus: 3:Illegal character ':' in log name>
2017-02-16 18:00:50 +0000 [info]: error code =
3
2017-02-16 18:00:50 +0000 [info]: error message =
"3:Illegal character ':' in log name"
2017-02-16 18:00:50 +0000 [info]: error details =
"Illegal character ':' in log name"
2017-02-16 18:00:50 +0000 [info]: error metadata =
{}
```

I was expecting something like

```
{
  0 => "3:Illegal character ':' in log name",
  1 => "3:Illegal character ':' in log name"
}
```

**Comment by blowmage** [comment] 2017-02-16 18:31
@swcloud I haven't been able to get any meaningful information in the BadStatus metadata attribute either. Even by calling the GRPC directly, and bypassing GAPIC. Perhaps this is a problem in the GRPC client? Can you escalate to the GRPC team?

**Comment by swcloud** [comment] 2017-02-17 06:22
Adding @apolcyn

**Comment by apolcyn** [comment] 2017-02-17 07:53
My first take on this is that it looks above gRPC. In general the `BadStatus` exception is thrown by the ruby client when a call results in a non-OK status. The metadata hash is for custom metadata and the details are for a custom message - they need to be filled in by the server that's returning the status. Is there expected metadata/message that isn't showing up here?

**Comment by blowmage** [comment] 2017-02-17 13:54
@apolcyn Yes, we expect the `WriteLogEntriesPartialErrors` data to be returned, per the documentation.

**Comment by qingling128** [comment] 2017-02-17 17:42
Originally I thought it was this [wrapping logic](https://github.com/googleapis/gax-ruby/blob/e8c66e40fe2881cf9b606f33acf4e8b7d13cefdc/lib/google/gax/api_callable.rb#L249) from `GRPC::BadStatus` to `GaxError` in the GAX lib that dropped the metadata info. But a closer look indicated for some reason the wrapping did not take effect, and I was able to rescue the `BadStatus` directly.

My current hunch is the information got dropped somewhere during the conversion from `google.rpc.Status` (where the Logging API server side code stores the info) to `GRPC::BadStatus`.

Line 742 and line 756 in [this method](https://github.com/grpc/grpc/blob/master/src/ruby/ext/grpc/rb_call.c#L724) `grpc_run_batch_stack_build_result` seems to be setting some metadata. And it looks fine to me, although the `initial_metadata` and `trailing_metadata` did confuse me a bit. I guess the `trailing_metadata` is what we need here?

Sadly I don't have enough knowledge to figure out what might be wrong...

**Comment by blowmage** [comment] 2017-02-17 18:02
@nicolasnoble @murgatroid99 Can you shed any light on the behavior of this Ruby client C code?

**Comment by nicolasnoble** [comment] 2017-02-17 18:08
Well, the proper contact point with regards to the specifics of how the C core works would maybe be @ctiller. At that point, @apolcyn holds as much information than us on the Ruby client C code.

If you want more insights about the C core, and if you suspect a problem in the C core, you'd need to run the whole thing with [debugging and tracing on](https://github.com/grpc/grpc/blob/master/doc/environment_variables.md) ? `GRPC_TRACE` can be set to "all".

**Comment by qingling128** [comment] 2017-02-21 23:33
Some updates:

I extracted the piece of code we use to make the call and test it on my dev box and a random GCP instance (the same one i used to run our agent in).

On my dev box (Ubiquity) it has the `WriteLogEntriesPartialErrors` I'm looking for in the metadata
```
lingshi@lingshi:~/testExample$ ruby testRubyClient.rb
Entries to write:
= [<Google::Logging::V2::LogEntry: proto_payload: nil, text_payload: "testing partial success", insert_id: "", json_payload: nil, http_request: nil, resource: <Google::Api::MonitoredResource: type: "gce_instance", labels: {"zone"=>"us-central1-b", "instance_id"=>"8501675777982250247"}>, timestamp: nil, severity: :DEFAULT, labels: {}, log_name: "projects/test-project/logs/b:ad", operation: nil>, <Google::Logging::V2::LogEntry: proto_payload: nil, text_payload: "testing partial success", insert_id: "", json_payload: nil, http_request: nil, resource: <Google::Api::MonitoredResource: type: "gce_instance", labels: {"zone"=>"us-central1-b", "instance_id"=>"8501675777982250247"}>, timestamp: nil, severity: :DEFAULT, labels: {}, log_name: "projects/test-project/logs/b:ad", operation: nil>, <Google::Logging::V2::LogEntry: proto_payload: nil, text_payload: "testing partial success", insert_id: "", json_payload: nil, http_request: nil, resource: <Google::Api::MonitoredResource: type: "gce_instance", labels: {"zone"=>"us-central1-b", "instance_id"=>"8501675777982250247"}>, timestamp: nil, severity: :DEFAULT, labels: {}, log_name: "projects/test-project/logs/good", operation: nil>]

error:
#<GRPC::InvalidArgument: 3:Illegal character ':' in log name>

error metadata =
{"google.rpc.debuginfo-bin"=>"\x12\xBE\x03[ORIGINAL ERROR] generic::invalid_argument: Illegal character ':' in log name [google.rpc.error_details_ext] { message: \"Illegal character \\':\\' in log name\" details { type_url: \"type.googleapis.com/google.logging.v2.WriteLogEntriesPartialErrors\" value: \"\\n)\\010\\000\\022%\\010\\003\\022!Illegal character \\':\\' in log name\\n)\\010\\001\\022%\\010\\003\\022!Illegal character \\':\\' in log name\\n\\034\\010\\002\\022\\030\\010\\007\\022\\024User not authorized.\" } }"}
```

While on the GCP instance it still shows empty metadata:
```
2017-02-21 23:13:57 +0000 [info]: Entries to write:
= [<Google::Logging::V2::LogEntry: proto_payload: nil, text_payload: "testing partial success", insert_id: "", json_payload: nil, http_request: nil, resource: <Google::Api::MonitoredResource: type: "gce_instance", labels: {"zone"=>"us-central1-b", "instance_id"=>"8501675777982250247"}>, timestamp: nil, severity: :DEFAULT, labels: {}, log_name: "projects/test-project/logs/b:ad", operation: nil>, <Google::Logging::V2::LogEntry: proto_payload: nil, text_payload: "testing partial success", insert_id: "", json_payload: nil, http_request: nil, resource: <Google::Api::MonitoredResource: type: "gce_instance", labels: {"zone"=>"us-central1-b", "instance_id"=>"8501675777982250247"}>, timestamp: nil, severity: :DEFAULT, labels: {}, log_name: "projects/test-project/logs/b:ad", operation: nil>, <Google::Logging::V2::LogEntry: proto_payload: nil, text_payload: "testing partial success", insert_id: "", json_payload: nil, http_request: nil, resource: <Google::Api::MonitoredResource: type: "gce_instance", labels: {"zone"=>"us-central1-b", "instance_id"=>"8501675777982250247"}>, timestamp: nil, severity: :DEFAULT, labels: {}, log_name: "projects/test-project/logs/good", operation: nil>]

2017-02-21 23:13:57 +0000 [info]: new error:
#<GRPC::BadStatus: 3:Illegal character ':' in log name>

2017-02-21 23:13:57 +0000 [info]: new error metadata =
{}
```

QUESTION: Is there some config / environment settings / params being passed in that controls whether "google.rpc.debuginfo-bin" would be returned? I tried to search it in the grpc code base, did not find anything relavant.

BTW, I set:

```
export GRPC_TRACE=all
export GRPC_VERBOSITY=DEBUG 
```

in both cases, but they should not influence the `metadata` in the response, I think.

The code snippet I was using is:

```
$ cat testRubyClient.rb
require 'grpc'
require 'google/apis'
require 'google/logging/v2/logging_pb'
require 'google/logging/v2/logging_services_pb'
require 'google/logging/v2/log_entry_pb'
require 'googleauth'

payload = 'testing partial success'
resource = Google::Api::MonitoredResource.new(
  type: 'gce_instance',
  labels: {
    'zone' => 'us-central1-b',
    'instance_id' => '8501675777982250247'
  }
)
good_log_name = 'projects/test-project/logs/good'
bad_log_name = 'projects/test-project/logs/b:ad'

entries = []
entry1 = Google::Logging::V2::LogEntry.new(
  resource: resource,
        text_payload: payload,
  log_name: bad_log_name
)
entry2 = Google::Logging::V2::LogEntry.new(
  resource: resource,
        text_payload: payload,
  log_name: bad_log_name
)
entry3 = Google::Logging::V2::LogEntry.new(
  resource: resource,
        text_payload: payload,
  log_name: good_log_name
)

entries.push(entry1)
entries.push(entry2)
entries.push(entry3)

puts "Entries to write:\n= #{entries.inspect}\n\n"

ssl_creds = GRPC::Core::ChannelCredentials.new
authentication = Google::Auth.get_application_default
creds = GRPC::Core::CallCredentials.new(authentication.updater_proc)
creds = ssl_creds.compose(creds)
client = Google::Logging::V2::LoggingServiceV2::Stub.new(
  'logging.googleapis.com', creds)

begin
  write_request = Google::Logging::V2::WriteLogEntriesRequest.new(
    log_name: 'projects/test-project/logs/normal',
    resource: resource,
    entries: entries,
    partial_success: true
  )
  response = client.write_log_entries(write_request)
rescue => error
  puts "error:\n#{error.inspect}\n"
  puts "error metadata =\n#{error.metadata.inspect}\n"
end
```

**Comment by apolcyn** [comment] 2017-02-23 04:55
@qingling128 I haven't reproduced yet but from the exception dumps on your dev box vs. gce, are there perhaps different versions of the grpc gem in these different environments? (The `GRPC::InvalidArgument` exception is introduced in v1.1.2, previous versions would throw the plain `GRPC::BadStatus`).

fyi:

> QUESTION: Is there some config / environment settings / params being passed in that controls whether "google.rpc.debuginfo-bin" would be returned? I tried to search it in the grpc code base, did not find anything relavant. 

AFAIK this should be showing up in both cases as long as it was sent.

Also it is correct that 
```
export GRPC_TRACE=all
export GRPC_VERBOSITY=DEBUG 
```
shouldn't be causing side effects with metadata.

**Comment by qingling128** [comment] 2017-02-23 22:42
I downgraded the grpc gem version on my dev box from `v1.1.2` to `v1.0.1` which is what the GCP instance has, and tried it again. Still the metadata showed up on my dev box. I did get `GRPC::BadStatus` instead of `GRPC::InvalidArgument` though.

```
lingshi@lingshi:~/testExample$ ruby testRubyClient.rb
Entries to write:
= [<Google::Logging::V2::LogEntry: proto_payload: nil, text_payload: "testing partial success", insert_id: "", json_payload: nil, http_request: nil, resource: <Google::Api::MonitoredResource: type: "gce_instance", labels: {"zone"=>"us-central1-b", "instance_id"=>"8501675777982250247"}>, timestamp: nil, severity: :DEFAULT, labels: {}, log_name: "projects/test-project/logs/b:ad", operation: nil>, <Google::Logging::V2::LogEntry: proto_payload: nil, text_payload: "testing partial success", insert_id: "", json_payload: nil, http_request: nil, resource: <Google::Api::MonitoredResource: type: "gce_instance", labels: {"zone"=>"us-central1-b", "instance_id"=>"8501675777982250247"}>, timestamp: nil, severity: :DEFAULT, labels: {}, log_name: "projects/test-project/logs/b:ad", operation: nil>, <Google::Logging::V2::LogEntry: proto_payload: nil, text_payload: "testing partial success", insert_id: "", json_payload: nil, http_request: nil, resource: <Google::Api::MonitoredResource: type: "gce_instance", labels: {"zone"=>"us-central1-b", "instance_id"=>"8501675777982250247"}>, timestamp: nil, severity: :DEFAULT, labels: {}, log_name: "projects/test-project/logs/good", operation: nil>]

error:
#<GRPC::BadStatus: 3:Illegal character ':' in log name>
error metadata =
{"google.rpc.debuginfo-bin"=>"\x12\xBE\x03[ORIGINAL ERROR] generic::invalid_argument: Illegal character ':' in log name [google.rpc.error_details_ext] { message: \"Illegal character \\':\\' in log name\" details { type_url: \"type.googleapis.com/google.logging.v2.WriteLogEntriesPartialErrors\" value: \"\\n)\\010\\000\\022%\\010\\003\\022!Illegal character \\':\\' in log name\\n)\\010\\001\\022%\\010\\003\\022!Illegal character \\':\\' in log name\\n\\034\\010\\002\\022\\030\\010\\007\\022\\024User not authorized.\" } }"}
```

**Comment by qingling128** [comment] 2017-02-27 21:46
Hi, did anyone have a chance to take a quick look? Or any other thoughts that I can try poking around myself?

**Comment by blowmage** [comment] 2017-02-27 23:55
@apolcyn ^

**Comment by apolcyn** [comment] 2017-02-28 03:18
The issue seen here is reproducing for me (with trailing metadata arriving locally but not on gce), but I'm not sure what the cause is so far.

noteworthy so far is with `export GRPC_VERBOSITY=DEBUG GRPC_TRACE=all,-queue_pluck,-queue_timeout`, running the repro here locally shows the "google.rpc.debuginfo-bin" trailer show up in c-core, while it doesn't on the gce instance

**Comment by blowmage** [comment] 2017-02-28 22:35
@apolcyn That's great you have a repro! Is it fair to say that this is an issue in GRPC on GCE? If so, would it make more sense to open a separate issue on GRPC and close this issue?

**Comment by apolcyn** [comment] 2017-02-28 23:52
This is still a guess at this point but to me it looks like the "google.rpc.debuginfo-bin" is actually not intended to arrive on GCE machines - this would be outside of GRPC's control. Please email me for internal details.

**Comment by qingling128** [comment] 2017-03-01 01:19
There is already an internal ticket for this. I've emailed you the number. We can have follow ups there.

Feel free to close this ticket. And thanks all for helping with the issue! :)

**Comment by blowmage** [comment] 2017-03-01 01:26
Will there be a public issue created where we can get status updates?

**Comment by blowmage** [comment] 2017-03-01 01:29
Closing since this has been identified as an upstream issue. Thanks all!

**Closed by blowmage** 2017-03-01 01:29 UTC
Labels: API: logging, core, gapic, Priority: P1, Status: Acknowledged, Type: Enhancement

**Comment by qingling128** [comment] 2017-03-01 16:33
Hi @blowmage, if this turns out to be an issue with GRPC, I'll create a public issue for status updates there. If this ends up being an issue with GCE machines, or if the details are internal only, I will give updates in this ticket when the problem is resolved.

**Comment by qingling128** [comment] 2017-03-30 23:53
Some update: 
Turned out the desired status metadata got stripped when clients were on public IP (e.g. on GCP). This has been fixed. The Logging API release including the fix went out on Mar 17.

**Comment by blowmage** [comment] 2017-03-31 00:07
Thanks @qingling128!
