### ISSUE TITLE
Update to ruby 2.5.0 fails

### ISSUE THREAD

**Issue by mberrueta** [GoogleCloudPlatform/google-cloud-ruby#1913] opened 2017-12-29 14:26 UTC
I'm using  that it's working well
- gem 'google-cloud'
- gem 'google-cloud-error_reporting'
- gem 'google-cloud-vision'

but trying to update to ruby 2.5.0 
```
rvm install ruby-2.5.0
rvm --default use 2.5.0
gem install bundle
bundle install
```
I'm getting the error.

`google-protobuf-3.2.0.2-universal-darwin requires ruby version < 2.5, which is incompatible with the current version, ruby 2.5.0p0`

there is a 3.5 version. probably upgrading this it can works.

## Environment

```
Bundler             1.16.1
  Platforms         ruby, x86_64-darwin-17
Ruby                2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]
  Full Path         /Users/matiasberrueta/.rvm/rubies/ruby-2.5.0/bin/ruby
  Config Dir        /Users/matiasberrueta/.rvm/rubies/ruby-2.5.0/etc
RubyGems            2.7.3
  Gem Home          /Users/matiasberrueta/.rvm/gems/ruby-2.5.0
  Gem Path          /Users/matiasberrueta/.rvm/gems/ruby-2.5.0:/Users/matiasberrueta/.rvm/gems/ruby-2.5.0@global
  User Path         /Users/matiasberrueta/.gem/ruby/2.5.0
  Bin Dir           /Users/matiasberrueta/.rvm/gems/ruby-2.5.0/bin
Tools
  Git               2.14.3 (Apple Git-98)
  RVM               1.29.2 (latest)
  rbenv             not installed
  chruby            not installed
  rubygems-bundler  (1.4.4)
```

## Bundler Build Metadata

```
Built At          2017-12-21
Git SHA           0034ef341
Released Version  true
```

## Bundler settings

```
gem.test
  Set for the current user (/Users/matiasberrueta/.bundle/config): "rspec"
gem.mit
  Set for the current user (/Users/matiasberrueta/.bundle/config): true
gem.coc
  Set for the current user (/Users/matiasberrueta/.bundle/config): true
```

### Gemfile

```ruby
source 'https://rubygems.org'
ruby '2.5.0'

gem 'bundler'
gem 'puma'

# Rails.
# gem 'rails', '~> 5.0.2'

gem 'actioncable'
gem 'actionmailer'
gem 'actionpack'
gem 'activejob'
gem 'activemodel'
gem 'activerecord'
gem 'activesupport'
gem 'rack'
gem 'railties'

gem 'active_model_otp'
gem 'active_null'

gem 'cancancan'
gem 'has_secure_token'
gem 'paranoia', '~> 2.2'
gem 'phone'
gem 'uuid'

gem 'attr_encrypted'
gem 'liquid'
gem 'mailgun-ruby'
gem 'memoist'
gem 'money-rails', git: 'https://github.com/RubyMoney/money-rails', branch: :master
gem 'mongoid'
gem 'pg'

gem 'cityhash'
gem 'fullcontact', '0.18.0'
gem 'i18n'
gem 'identity_cache', git: 'https://github.com/Shopify/identity_cache/', branch: :master
gem 'redis'
gem 'redis-objects'
gem 'redis-rails'
gem 'request_store'
gem 'sendinblue'
gem 'slack-notifier'
gem 'statesman'

gem 'knock', git: 'https://github.com/mustela/knock', branch: :removing_rails_dep

gem 'sidekiq'
gem 'sidekiq-scheduler'

gem 'algoliasearch-rails'
gem 'exifr'
gem 'fastimage'
gem 'google-protobuf'
gem 'google-cloud'
gem 'google-cloud-error_reporting'
gem 'google-cloud-vision'

# Views
gem 'active_model_serializers', '~> 0.10'
gem 'oj' # Faster JSONing
gem 'rack-accept-default'
gem 'rack-accept_headers', '~> 0.5'
gem 'versioncake', '>= 2.4'

gem 'kaminari' # Pagination

# Cli - importers
gem 'activerecord-import'
gem 'bulk_insert'
gem 'formatador'
gem 'highline'
gem 'namae'
gem 'tty-spinner'

gem 'newrelic_rpm'

# # To use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.7'

# Error reporting and metrics
gem 'rollbar'

# Auth
gem 'rack-cors', require: 'rack/cors'

# Heroku lib
gem 'rails_12factor', group: :production

gem 'rqrcode'
gem 's3'

# Gateways
gem 'braintree'

# Reporting
gem 'fast_excel'

group :development do
  gem 'city-state' # only used to create the algolia indexes, that are without specific environment
  gem 'derailed'
  gem 'guard-brakeman'
  gem 'guard-bundler', require: false
  gem 'guard-cucumber'
  gem 'guard-rails'
  gem 'guard-rspec', require: false
  gem 'guard-rubocop'
  gem 'spring'
  gem 'spring-commands-cucumber'
  gem 'spring-commands-rspec'
end

group :development, :test do
  gem 'awesome_print', require: 'ap'
  gem 'brakeman', require: false
  gem 'bullet'
  gem 'bundler-audit', require: false
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'mock_redis'
  # gem 'rake'
  # Don't change the order of these 2 gems
  gem 'pry-rails'
  # rubocop:disable Bundler/OrderedGems
  gem 'pry-doc'
  gem 'pry-byebug'
  # rubocop:enable Bundler/OrderedGems
  gem 'pry-inline'
  gem 'pry-rescue'
  gem 'pry-stack_explorer'
  # gem 'pry-state' make errors with class Printer
  gem 'rails_best_practices', require: false
  gem 'rspec-expectations'
  gem 'rspec-rails'
  gem 'rubocop', '~> 0.48.1', require: false
  # only load for seek n+1 issues
  gem 'n_1_finder'
  # is not working and breake binding.pry
  # gem 'debase'
  # gem 'ruby-debug-ide'
end

group :test do
  gem 'cucumber-rails', require: false
  gem 'database_cleaner'
  gem 'rails-controller-testing'
  gem 'simplecov'
  gem 'simplecov-csv'
  gem 'webmock'
end
```

### Gemfile.lock

```
GIT
  remote: https://github.com/RubyMoney/money-rails
  revision: b74c8e06e2133b4d37ca4e3c86f52b70ab59f6d3
  branch: master
  specs:
    money-rails (1.9.0)
      activesupport (>= 3.0)
      monetize (~> 1.7.0)
      money (~> 6.10.0)
      railties (>= 3.0)

GIT
  remote: https://github.com/Shopify/identity_cache/
  revision: d2389af95e432d838e23985b1cba0fbd04e8751d
  branch: master
  specs:
    identity_cache (0.5.1)
      activerecord (~> 5.0)
      ar_transaction_changes (~> 1.0)

GIT
  remote: https://github.com/mustela/knock
  revision: 5d07cee0b7947cf636134ccefdd2b1908163d6c9
  branch: removing_rails_dep
  specs:
    knock (2.1.1)
      bcrypt (~> 3.1)
      jwt (~> 1.5)

GEM
  remote: https://rubygems.org/
  specs:
    actioncable (5.1.4)
      actionpack (= 5.1.4)
      nio4r (~> 2.0)
      websocket-driver (~> 0.6.1)
    actionmailer (5.1.4)
      actionpack (= 5.1.4)
      actionview (= 5.1.4)
      activejob (= 5.1.4)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (5.1.4)
      actionview (= 5.1.4)
      activesupport (= 5.1.4)
      rack (~> 2.0)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (5.1.4)
      activesupport (= 5.1.4)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.3)
    active_model_otp (1.2.0)
      activemodel
      rotp
    active_model_serializers (0.10.7)
      actionpack (>= 4.1, < 6)
      activemodel (>= 4.1, < 6)
      case_transform (>= 0.2)
      jsonapi-renderer (>= 0.1.1.beta1, < 0.3)
    active_null (1.0.0)
      naught (~> 1.0)
    activejob (5.1.4)
      activesupport (= 5.1.4)
      globalid (>= 0.3.6)
    activemodel (5.1.4)
      activesupport (= 5.1.4)
    activerecord (5.1.4)
      activemodel (= 5.1.4)
      activesupport (= 5.1.4)
      arel (~> 8.0)
    activerecord-import (0.21.0)
      activerecord (>= 3.2)
    activesupport (5.1.4)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (~> 0.7)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
    addressable (2.5.2)
      public_suffix (>= 2.0.2, < 4.0)
    algoliasearch (1.18.2)
      httpclient (~> 2.8.3)
      json (>= 1.5.1)
    algoliasearch-rails (1.20.3)
      algoliasearch (>= 1.17.0, < 2.0.0)
      json (>= 1.5.1)
    ar_transaction_changes (1.1.2)
      activerecord (>= 4.2.4, < 6.0)
    arel (8.0.0)
    ast (2.3.0)
    attr_encrypted (3.0.3)
      encryptor (~> 3.0.0)
    awesome_print (1.8.0)
    bcrypt (3.1.11)
    benchmark-ips (2.7.2)
    binding_of_caller (0.7.3)
      debug_inspector (>= 0.0.1)
    braintree (2.80.1)
      builder (>= 2.0.0)
    brakeman (4.0.1)
    bson (4.2.2)
    builder (3.2.3)
    bulk_insert (1.6.0)
      activerecord (>= 4.1.0)
    bullet (5.6.1)
      activesupport (>= 3.0.0)
      uniform_notifier (~> 1.10.0)
    bundler-audit (0.6.0)
      bundler (~> 1.2)
      thor (~> 0.18)
    byebug (9.1.0)
    cancancan (2.1.2)
    capybara (2.16.1)
      addressable
      mini_mime (>= 0.1.3)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      xpath (~> 2.0)
    case_transform (0.2)
      activesupport
    chunky_png (1.3.8)
    city-state (0.0.13)
      rubyzip (~> 1.1)
    cityhash (0.9.0)
    code_analyzer (0.4.8)
      sexp_processor
    coderay (1.1.2)
    concurrent-ruby (1.0.5)
    connection_pool (2.2.1)
    crack (0.4.3)
      safe_yaml (~> 1.0.0)
    crass (1.0.3)
    cucumber (2.2.0)
      builder (>= 2.1.2)
      cucumber-core (~> 1.3.0)
      cucumber-wire (~> 0.0.1)
      diff-lcs (>= 1.1.3)
      event-bus (~> 0.1.0)
      gherkin3 (~> 3.1.0)
      multi_json (>= 1.7.5, < 2.0)
      multi_test (>= 0.1.2)
    cucumber-core (1.3.1)
      gherkin3 (~> 3.1.0)
    cucumber-rails (1.5.0)
      capybara (>= 1.1.2, < 3)
      cucumber (>= 1.3.8, < 4)
      mime-types (>= 1.17, < 4)
      nokogiri (~> 1.5)
      railties (>= 4, < 5.2)
    cucumber-wire (0.0.1)
    database_cleaner (1.6.2)
    debug_inspector (0.0.3)
    derailed (0.1.0)
      derailed_benchmarks
    derailed_benchmarks (1.3.2)
      benchmark-ips (~> 2)
      get_process_mem (~> 0)
      heapy (~> 0)
      memory_profiler (~> 0)
      rack (>= 1)
      rake (> 10, < 13)
      thor (~> 0.19)
    diff-lcs (1.3)
    docile (1.1.5)
    domain_name (0.5.20170404)
      unf (>= 0.0.5, < 1.0.0)
    encryptor (3.0.0)
    erubi (1.7.0)
    erubis (2.7.0)
    et-orbi (1.0.8)
      tzinfo
    event-bus (0.1.0)
    exifr (1.3.2)
    factory_bot (4.8.2)
      activesupport (>= 3.0.0)
    factory_bot_rails (4.8.2)
      factory_bot (~> 4.8.2)
      railties (>= 3.0.0)
    faker (1.8.4)
      i18n (~> 0.5)
    faraday (0.11.0)
      multipart-post (>= 1.2, < 3)
    faraday_middleware (0.12.2)
      faraday (>= 0.7.4, < 1.0)
    fast_excel (0.2.3)
      ffi (> 1.9, < 2)
    fastimage (2.1.0)
    ffi (1.9.18)
    formatador (0.2.5)
    fullcontact (0.18.0)
      faraday (~> 0.11.0)
      faraday_middleware (>= 0.10)
      hashie (>= 2.0, < 4.0)
    get_process_mem (0.2.1)
    gherkin3 (3.1.2)
    globalid (0.4.1)
      activesupport (>= 4.2.0)
    guard (2.14.1)
      formatador (>= 0.2.4)
      listen (>= 2.7, < 4.0)
      lumberjack (~> 1.0)
      nenv (~> 0.1)
      notiffany (~> 0.0)
      pry (>= 0.9.12)
      shellany (~> 0.0)
      thor (>= 0.18.1)
    guard-brakeman (0.8.3)
      brakeman (>= 2.1.1)
      guard (>= 2.0.0)
    guard-bundler (2.1.0)
      bundler (~> 1.0)
      guard (~> 2.2)
      guard-compat (~> 1.1)
    guard-compat (1.2.1)
    guard-cucumber (2.1.2)
      cucumber (~> 2.0)
      guard-compat (~> 1.0)
      nenv (~> 0.1)
    guard-rails (0.8.1)
      guard (~> 2.11)
      guard-compat (~> 1.0)
    guard-rspec (4.7.3)
      guard (~> 2.1)
      guard-compat (~> 1.1)
      rspec (>= 2.99.0, < 4.0)
    guard-rubocop (1.3.0)
      guard (~> 2.0)
      rubocop (~> 0.20)
    has_secure_token (1.0.0)
      activerecord (>= 3.0)
    hashdiff (0.3.7)
    hashie (3.5.6)
    heapy (0.1.3)
    highline (1.7.10)
    http-cookie (1.0.3)
      domain_name (~> 0.5)
    httparty (0.15.6)
      multi_xml (>= 0.5.2)
    httpclient (2.8.3)
    i18n (0.9.1)
      concurrent-ruby (~> 1.0)
    interception (0.5)
    json (2.1.0)
    jsonapi-renderer (0.2.0)
    jwt (1.5.6)
    kaminari (1.1.1)
      activesupport (>= 4.1.0)
      kaminari-actionview (= 1.1.1)
      kaminari-activerecord (= 1.1.1)
      kaminari-core (= 1.1.1)
    kaminari-actionview (1.1.1)
      actionview
      kaminari-core (= 1.1.1)
    kaminari-activerecord (1.1.1)
      activerecord
      kaminari-core (= 1.1.1)
    kaminari-core (1.1.1)
    liquid (4.0.0)
    listen (3.1.5)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
      ruby_dep (~> 1.2)
    loofah (2.1.1)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    lumberjack (1.0.12)
    macaddr (1.7.1)
      systemu (~> 2.6.2)
    mail (2.7.0)
      mini_mime (>= 0.1.1)
    mailgun-ruby (1.1.8)
      rest-client (~> 2.0)
    memoist (0.16.0)
    memory_profiler (0.9.8)
    method_source (0.9.0)
    mime-types (3.1)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2016.0521)
    mini_mime (1.0.0)
    mini_portile2 (2.3.0)
    minitest (5.10.3)
    mock_redis (0.17.3)
    monetize (1.7.0)
      money (~> 6.9)
    money (6.10.0)
      i18n (>= 0.6.4, < 1.0)
    mongo (2.4.3)
      bson (>= 4.2.1, < 5.0.0)
    mongoid (6.2.1)
      activemodel (~> 5.1)
      mongo (>= 2.4.1, < 3.0.0)
    multi_json (1.12.2)
    multi_test (0.1.2)
    multi_xml (0.6.0)
    multipart-post (2.0.0)
    n_1_finder (0.0.6)
    namae (0.11.3)
    naught (1.1.0)
    nenv (0.3.0)
    netrc (0.11.0)
    newrelic_rpm (4.6.0.338)
    nio4r (2.1.0)
    nokogiri (1.8.1)
      mini_portile2 (~> 2.3.0)
    notiffany (0.1.1)
      nenv (~> 0.1)
      shellany (~> 0.0)
    oj (3.3.9)
    paranoia (2.4.0)
      activerecord (>= 4.0, < 5.2)
    parser (2.4.0.2)
      ast (~> 2.3)
    pg (0.21.0)
    phone (1.2.3)
    powerpack (0.1.1)
    proxies (0.2.1)
    pry (0.11.3)
      coderay (~> 1.1.0)
      method_source (~> 0.9.0)
    pry-byebug (3.5.1)
      byebug (~> 9.1)
      pry (~> 0.10)
    pry-doc (0.11.1)
      pry (~> 0.9)
      yard (~> 0.9)
    pry-inline (1.0.4)
      pry (> 0.10.0, < 0.12.0)
      unicode (~> 0.4.4)
    pry-rails (0.3.6)
      pry (>= 0.10.4)
    pry-rescue (1.4.5)
      interception (>= 0.5)
      pry
    pry-stack_explorer (0.4.9.2)
      binding_of_caller (>= 0.7)
      pry (>= 0.9.11)
    public_suffix (3.0.1)
    puma (3.11.0)
    rack (2.0.3)
    rack-accept-default (0.0.2)
      rack
    rack-accept_headers (0.5.1)
      rack (>= 1.5.2)
    rack-cors (1.0.2)
    rack-protection (2.0.0)
      rack
    rack-test (0.8.2)
      rack (>= 1.0, < 3)
    rails-controller-testing (1.0.2)
      actionpack (~> 5.x, >= 5.0.1)
      actionview (~> 5.x, >= 5.0.1)
      activesupport (~> 5.x)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.0.3)
      loofah (~> 2.0)
    rails_12factor (0.0.3)
      rails_serve_static_assets
      rails_stdout_logging
    rails_best_practices (1.19.0)
      activesupport
      code_analyzer (>= 0.4.8)
      erubis
      i18n
      json
      require_all
      ruby-progressbar
    rails_serve_static_assets (0.0.5)
    rails_stdout_logging (0.0.5)
    railties (5.1.4)
      actionpack (= 5.1.4)
      activesupport (= 5.1.4)
      method_source
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rainbow (2.2.2)
      rake
    rake (12.3.0)
    rb-fsevent (0.10.2)
    rb-inotify (0.9.10)
      ffi (>= 0.5.0, < 2)
    redis (3.3.5)
    redis-actionpack (5.0.2)
      actionpack (>= 4.0, < 6)
      redis-rack (>= 1, < 3)
      redis-store (>= 1.1.0, < 2)
    redis-activesupport (5.0.4)
      activesupport (>= 3, < 6)
      redis-store (>= 1.3, < 2)
    redis-objects (1.3.1)
      redis (~> 3.3)
    redis-rack (2.0.3)
      rack (>= 1.5, < 3)
      redis-store (>= 1.2, < 2)
    redis-rails (5.0.2)
      redis-actionpack (>= 5.0, < 6)
      redis-activesupport (>= 5.0, < 6)
      redis-store (>= 1.2, < 2)
    redis-store (1.4.1)
      redis (>= 2.2, < 5)
    request_store (1.3.2)
    require_all (1.4.0)
    rest-client (2.0.2)
      http-cookie (>= 1.0.2, < 2.0)
      mime-types (>= 1.16, < 4.0)
      netrc (~> 0.8)
    rollbar (2.15.5)
      multi_json
    rotp (3.3.0)
    rqrcode (0.10.1)
      chunky_png (~> 1.0)
    rspec (3.7.0)
      rspec-core (~> 3.7.0)
      rspec-expectations (~> 3.7.0)
      rspec-mocks (~> 3.7.0)
    rspec-core (3.7.0)
      rspec-support (~> 3.7.0)
    rspec-expectations (3.7.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.7.0)
    rspec-mocks (3.7.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.7.0)
    rspec-rails (3.7.2)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      railties (>= 3.0)
      rspec-core (~> 3.7.0)
      rspec-expectations (~> 3.7.0)
      rspec-mocks (~> 3.7.0)
      rspec-support (~> 3.7.0)
    rspec-support (3.7.0)
    rubocop (0.48.1)
      parser (>= 2.3.3.1, < 3.0)
      powerpack (~> 0.1)
      rainbow (>= 1.99.1, < 3.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (~> 1.0, >= 1.0.1)
    ruby-progressbar (1.9.0)
    ruby_dep (1.5.0)
    rubyzip (1.2.1)
    rufus-scheduler (3.4.2)
      et-orbi (~> 1.0)
    s3 (0.3.25)
      proxies (~> 0.2.0)
    safe_yaml (1.0.4)
    sendinblue (2.4)
      httparty
      json
    sexp_processor (4.10.0)
    shellany (0.0.1)
    sidekiq (5.0.5)
      concurrent-ruby (~> 1.0)
      connection_pool (~> 2.2, >= 2.2.0)
      rack-protection (>= 1.5.0)
      redis (>= 3.3.4, < 5)
    sidekiq-scheduler (2.1.10)
      redis (>= 3, < 5)
      rufus-scheduler (~> 3.2)
      sidekiq (>= 3)
      tilt (>= 1.4.0)
    simplecov (0.15.1)
      docile (~> 1.1.0)
      json (>= 1.8, < 3)
      simplecov-html (~> 0.10.0)
    simplecov-csv (0.1.3)
      simplecov
    simplecov-html (0.10.2)
    slack-notifier (2.3.1)
    spring (2.0.2)
      activesupport (>= 4.2)
    spring-commands-cucumber (1.0.1)
      spring (>= 0.9.1)
    spring-commands-rspec (1.0.4)
      spring (>= 0.9.1)
    statesman (3.2.0)
    systemu (2.6.5)
    thor (0.20.0)
    thread_safe (0.3.6)
    tilt (2.0.8)
    tty-cursor (0.5.0)
    tty-spinner (0.7.0)
      tty-cursor (>= 0.5.0)
    tzinfo (1.2.4)
      thread_safe (~> 0.1)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.7.4)
    unicode (0.4.4.4)
    unicode-display_width (1.3.0)
    uniform_notifier (1.10.0)
    uuid (2.3.8)
      macaddr (~> 1.0)
    versioncake (3.3.0)
      actionpack (>= 3.2)
      activesupport (>= 3.2)
      railties (>= 3.2)
      tzinfo
    webmock (3.1.1)
      addressable (>= 2.3.6)
      crack (>= 0.3.2)
      hashdiff
    websocket-driver (0.6.5)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.3)
    xpath (2.1.0)
      nokogiri (~> 1.3)
    yard (0.9.12)

PLATFORMS
  ruby

DEPENDENCIES
  actioncable
  actionmailer
  actionpack
  active_model_otp
  active_model_serializers (~> 0.10)
  active_null
  activejob
  activemodel
  activerecord
  activerecord-import
  activesupport
  algoliasearch-rails
  attr_encrypted
  awesome_print
  bcrypt (~> 3.1.7)
  braintree
  brakeman
  bulk_insert
  bullet
  bundler
  bundler-audit
  cancancan
  city-state
  cityhash
  cucumber-rails
  database_cleaner
  derailed
  exifr
  factory_bot_rails
  faker
  fast_excel
  fastimage
  formatador
  fullcontact (= 0.18.0)
  guard-brakeman
  guard-bundler
  guard-cucumber
  guard-rails
  guard-rspec
  guard-rubocop
  has_secure_token
  highline
  i18n
  identity_cache!
  kaminari
  knock!
  liquid
  mailgun-ruby
  memoist
  mock_redis
  money-rails!
  mongoid
  n_1_finder
  namae
  newrelic_rpm
  oj
  paranoia (~> 2.2)
  pg
  phone
  pry-byebug
  pry-doc
  pry-inline
  pry-rails
  pry-rescue
  pry-stack_explorer
  puma
  rack
  rack-accept-default
  rack-accept_headers (~> 0.5)
  rack-cors
  rails-controller-testing
  rails_12factor
  rails_best_practices
  railties
  redis
  redis-objects
  redis-rails
  request_store
  rollbar
  rqrcode
  rspec-expectations
  rspec-rails
  rubocop (~> 0.48.1)
  s3
  sendinblue
  sidekiq
  sidekiq-scheduler
  simplecov
  simplecov-csv
  slack-notifier
  spring
  spring-commands-cucumber
  spring-commands-rspec
  statesman
  tty-spinner
  uuid
  versioncake (>= 2.4)
  webmock

RUBY VERSION
   ruby 2.5.0p0

BUNDLED WITH
   1.16.1
```

**Comment by mberrueta** [comment] 2017-12-29 14:30
with 3.5 also fails

`google-protobuf-3.5.0-universal-darwin requires ruby version < 2.5, which is incompatible with the current version, ruby 2.5.0p0`

**Comment by blowmage** [comment] 2017-12-29 17:44
Hi @mberrueta, thanks for opening this issue. The problem is that both the `grpc` and `google-protobuf` gems you are using are pre-compiled and they don't have support for Ruby 2.5 since it was just released. We expect new versions of both these gems that will add support for Ruby 2.5 sometime early January.

One workaround may be to compile these gems by following [these instructions](https://github.com/grpc/grpc/tree/master/src/ruby#build-from-source).

/cc @geigerj

**Comment by mberrueta** [comment] 2017-12-29 20:36
thanks man!

**Comment by geigerj** [comment] 2018-01-03 19:38
GRPC has filed https://github.com/grpc/grpc/issues/13908 to track a release supporting Ruby 2.5.

**Comment by blowmage** [comment] 2018-01-08 19:24
I am closing this issue as there is an upstream issue for this (grpc/grpc#13908) and we don't anticipate any changes needed when that issue is fixed.

**Closed by blowmage** 2018-01-08 19:24 UTC
Labels: grpc, priority: p2, type: bug
