### ISSUE TITLE
Add the README content to Monitoring landing page

### ISSUE THREAD

**Issue by omaray** [GoogleCloudPlatform/google-cloud-ruby#1611] opened 2017-07-25 20:57 UTC
**ISSUE**
There is currently no information on the landing page of the Monitoring API in the client library reference documentation:

![image](https://user-images.githubusercontent.com/6609430/28593297-b1d07c0c-7140-11e7-8287-4de15cf131c9.png)

**EXPECTED RESULT**
Given that we have a [README for the Monitoring API](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-monitoring/README.md) already with good information, we could use that same content and place it on that landing page in the Client Library reference. This will help our users know how to get started.

**Comment by thagomizer** [comment] 2017-07-25 21:01
Dupe of this: https://github.com/GoogleCloudPlatform/google-cloud-ruby/issues/1470

**Comment by quartzmo** [comment] 2017-08-07 16:59
Closing as duplicate.

**Closed by quartzmo** 2017-08-07 16:59 UTC
Labels: API: monitoring
