### ISSUE TITLE
[pubsub] immediate:false does not see new msgs promptly

### ISSUE THREAD

**Issue by mpcm** [GoogleCloudPlatform/google-cloud-ruby#1413] opened 2017-04-08 03:53 UTC
When I have a statement like the below, it readily see's messages as they come in, even with gaps were there are no messages can be delivered.
`messages = sub.pull( immediate: true, max: 1, autoack: false )`

But with this statement, I'm seeing it sit on that line... even as messages pile up that could be acted upon.
`messages = sub.pull( immediate: false, max: 1, autoack: false )`

Is this expected?

Pattern: I have a loop blocking on getting a msg, once it gets a msg... it acks that msg, then does the related work, and then reloops. I believe it used to still see new messages as they came in...

    google-cloud-pubsub (0.24.0)
      google-cloud-core (~> 1.0)
      google-gax (~> 0.8.0)
      grpc-google-iam-v1 (~> 0.6.8)

**Comment by mpcm** [comment] 2017-04-08 04:10
https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-pubsub/lib/google/cloud/pubsub/subscription.rb#L186 seems to support my expectation.

**Comment by blowmage** [comment] 2017-04-10 14:33
@landrito Can you take this since @swcloud is out? The behavior described is coming from the Pub/Sub service. The client is waiting on a response from the server. The ruby documentation referenced is taken from the [service documentation](https://cloud.google.com/pubsub/docs/reference/rpc/google.pubsub.v1#google.pubsub.v1.PullRequest). Did the service make any changes to the API implementation lately?

**Comment by landrito** [comment] 2017-04-24 19:45
I am having a bit of trouble trying to recreate 😞 . From my simple tests. If I create a subscriber and pull using `( immediate: false, max: 1, autoack: false )`, then publish a single message, the subscriber takes a bit of time to get the published message (I have seen it take as long as 7 minutes). But if I subscribe many messages, the subscriber gets the messages very quickly.

Am I missing something?

Subscriber:
```rb
# Imports the Google Cloud client library
require "google/cloud/pubsub"

# Your Google Cloud Platform project ID
project_id = "landrito-project"

# Instantiates a client
pubsub = Google::Cloud::Pubsub.new project: project_id

# # The name for the new topic
topic_name = "mytopic"

# # Creates the new topic
topic = pubsub.topic topic_name

puts "Topic #{topic.name} created."

# Retrieve a subscription
sub = topic.subscription "mytopic-sub"

loop do
  p Time.now

  messages = sub.pull( immediate: false, max: 1, autoack: false )

  messages.each do |msg|
    p msg
    msg.acknowledge!
  end
end
```

Publisher:
```rb
# Imports the Google Cloud client library
require "google/cloud/pubsub"

# Your Google Cloud Platform project ID
project_id = "landrito-project"

# Instantiates a client
pubsub = Google::Cloud::Pubsub.new project: project_id

# # The name for the new topic
topic_name = "mytopic"

# # Creates the new topic
topic = pubsub.topic topic_name

p topic.publish "Doing the thing at #{Time.now}"  
```

**Comment by geigerj** [comment] 2017-08-07 17:06
@blowmage Are you still seeing this behavior in your recent development on Pub/Sub?

**Comment by blowmage** [comment] 2017-08-07 17:40
No, I don't think I've ever seen this behavior. I've published messages and been able to pull them immediately many, many times. We even have acceptance tests that do this. I'm not sure why this user saw this delayed behavior, but I'm certain it isn't anything in the ruby client.

**Comment by geigerj** [comment] 2017-08-07 17:43
Closing this issue, since we haven't been able to reproduce. @mpcm, if you're still running into this issue, please re-open with some sample code to help us reproduce.

**Closed by geigerj** 2017-08-07 17:43 UTC
Labels: API: pubsub, Status: Acknowledged, Type: Question

**Comment by blowmage** [comment] 2017-08-07 17:46
@mpcm, FWIW, I think the upcoming Subscriber object is going to be very beneficial for your use case.
