### ISSUE TITLE
Datastore / grpc: 413:Request Entity Too Large reported as GRPC::Unavailable: 14

### ISSUE THREAD

**Issue by timanovsky** [GoogleCloudPlatform/google-cloud-ruby#1325] opened 2017-03-11 03:47 UTC
So we recently started seeing this new error:
`GRPC::Unavailable: 14:413:Request Entity Too Large` two problems with it:

1) not completely sure what it means, there is other error code for oversized entities:
`Google::Cloud::InvalidArgumentError: 3:The value of property "data" is longer than 1048487 bytes.` Documentation says nothing about code 413.

2) It is reported as `Unavailable` class, so presumably retryable however whole context makes me think it is probably not.

I'm not sure it is ruby gem level problem, may be more of grpc stack.

**Comment by bmclean** [comment] 2017-03-13 15:24
I am curious, did you try a retry and was it successful? I understand the confusion as HTTP 413 errors (Request Entity Too Large) mean the request entity is larger than the server is willing or able to process.

**Comment by quartzmo** [comment] 2017-03-13 17:04
@timanovsky Is the issue here that the `Unavailable` wrapper is incorrect for `413 Payload Too Large`?

**Comment by danoscarmike** [comment] 2017-03-13 18:42
@lukesneeringer @swcloud: @blowmage suggests this must be coming from the datastore service itself.  GRPC returning unavailable (14) with a description detailing an HTTP error (413).  Can you please review with datastore team?

**Comment by timanovsky** [comment] 2017-03-13 20:02
@quartzmo Yes, `Unavailable` assumes it is retriable I think
@bmclean Yes, tried to retry this without success

**Comment by swcloud** [comment] 2017-03-14 06:17
Currently the client library only does retry for non_idempotent methods. We have to yet propagate the commit here https://github.com/googleapis/googleapis/commit/b01f986d341005ee0c98ac3d3af764d974715091

to the client library.

**Comment by swcloud** [comment] 2017-03-15 22:22
@timanovsky the retry for non_idempotent methods for Unavailable has been merged to master. Please give it another try.

**Comment by timanovsky** [comment] 2017-03-15 22:26
@swcloud I think there is a misunderstanding here. I don't have problems with the library (not) retrying the error, we use our own retry layar. The problem is that fatal error is reported as `Unavailable` which has retriable semantics.

**Comment by swcloud** [comment] 2017-03-15 22:41
@timanovsky Can you let us know which API method call caused the error? Any code snippet to reproduce the error? That'll help a lot to investigate.

**Comment by timanovsky** [comment] 2017-03-15 22:43
@swcloud It id batch `commit` operation which contains a couple of `save` operations

**Comment by blowmage** [comment] 2017-03-16 17:16
@timanovsky Do you have a full backtrace?

**Comment by swcloud** [comment] 2017-03-23 23:13
@timanovsky According to https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html,

> 10.4.14 413 Request Entity Too Large
> 
> The server is refusing to process a request because the request entity is larger than the server is willing or able to process. The server MAY close the connection to prevent the client from continuing the request.
> 
> If the condition is temporary, the server SHOULD include a Retry- After header field to indicate that it is temporary and after what time the client MAY try again.

Based on the above, returning Unavailable hence triggering retry seems to be reasonable to me.

**Comment by blowmage** [comment] 2017-03-24 00:06
@swcloud You linked to the HTTP/1.1 spec, but GRPC is built on top of HTTP/2, right? Why is the GRPC request (using HTTP/2) receiving a HTTP/1.1 response?

**Comment by timanovsky** [comment] 2017-03-24 03:19
Guys, I created GRPC ticket for that - https://github.com/grpc/grpc/issues/10213
This one can probably closed,  I don't think anything can be done at this level.

@swcloud Except that a) user does not have visibility of `Retry- After` header b) retries (which we do by default) do not help

**Comment by swcloud** [comment] 2017-03-30 00:28
@blowmage HTTP/2 will use the same status code as HTTP/1.1. https://http2.github.io/

Close this issue since it should be resolved at grpc level.

**Closed by swcloud** 2017-03-30 00:28 UTC
Labels: API: datastore, Priority: P1, Status: Acknowledged, Type: Bug
