### ISSUE TITLE
MetricServiceClient#create_time_series docs should specify what type of Array

### ISSUE THREAD

**Issue by thagomizer** [GoogleCloudPlatform/google-cloud-ruby#1476] opened 2017-05-16 16:06 UTC
The MetricServiceClient#create_time_series docs say time_series is an Array but it doesn't say an array of *what*. Since the type is very specific ProtoBuf::RepeatedField we should specify that (and link to the documentation for that class). I tried several different arrays of Standard Library types and none of them worked or produced useful errors. 

[https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-monitoring/v0.24.0/google/cloud/monitoring/v3/metricserviceclient?method=create_time_series-instance](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-monitoring/v0.24.0/google/cloud/monitoring/v3/metricserviceclient?method=create_time_series-instance)

**Comment by geigerj** [comment] 2017-05-31 17:49
Tracking feature request to GAPIC code generator here: https://github.com/googleapis/toolkit/issues/1311

**Comment by geigerj** [comment] 2017-05-31 17:58
https://github.com/googleapis/toolkit/issues/1313 for missing enum types

**Comment by geigerj** [comment] 2017-08-07 17:53
Closing as duplicate of googleapis/toolkit#1311, googleapis/toolkit#1313, since this will be fixed in the GAPIC generator, rather than here.

**Closed by geigerj** 2017-08-07 17:53 UTC
Labels: API: monitoring
