### ISSUE TITLE
Still showing "gcloud" in the title of client lib landing page

### ISSUE THREAD

**Issue by omaray** [GoogleCloudPlatform/google-cloud-ruby#1140] opened 2016-12-15 03:30 UTC
We should update the title to `google-cloud-ruby`

![image](https://cloud.githubusercontent.com/assets/6609430/21210914/c7c43128-c233-11e6-9b2f-7d98859d92a4.png)

**Comment by quartzmo** [comment] 2016-12-15 04:03
I believe this is a duplicate of #945, and that the fix must be in gcloud-common per GoogleCloudPlatform/gcloud-common#195.

**Comment by quartzmo** [comment] 2016-12-15 04:09
@omaray I'll see if I can produce a fix tomorrow for GoogleCloudPlatform/gcloud-common#195.

**Closed** 2016-12-21 02:12 UTC
Labels: docs
