### ISSUE TITLE
Datastore: Google::Cloud::InvalidArgumentError: 3:The referenced transaction has expired or is no longer valid

### ISSUE THREAD

**Issue by whitmanc** [GoogleCloudPlatform/google-cloud-ruby#873] opened 2016-08-31 20:35 UTC
Hello. What does this error mean? Is there any way to find further information about it? 

This only happens on `0.12.2`, and not on `0.7.2`, and only on a staging server, not locally. 

Any idea what might be going on? Currently, the only way to fix this is to run `0.7.2`, but `0.7.2` won't work locally then due to an auth error. Something seems seriously wrong

**Comment by blowmage** [comment] 2016-08-31 20:38
Ho @whitmanc, thanks for opening the issue. Does this happen all the time? Or just for specific operations? Can you give us some code that reproduces the error?

**Comment by blowmage** [comment] 2016-08-31 20:39
A backtrack would also be very helpful.

**Comment by whitmanc** [comment] 2016-08-31 20:45
We're working to try to extract code which can reproduce it for you. Is there anything internally in particular that might raise the error?
 cc @emboss

**Comment by blowmage** [comment] 2016-08-31 20:48
The error is coming from the Datastore service. So it is either something you are sending, or something the google-cloud library is sending. It depends on what endpoint you are hitting when the error occurs. The more info you can give us the more we can help you with this.

**Comment by whitmanc** [comment] 2016-08-31 20:49
@blowmage Preparing stack trace, code snippets, etc. for you now as your message was received :)

**Comment by whitmanc** [comment] 2016-08-31 20:52
@blowmage In the meantime, let me share some of the code with you and the full stack trace:

```
Google::Cloud::InvalidArgumentError: 3:The referenced transaction has expired or is no longer valid.
	from /home/deploy/apps/bilz-admin-app/shared/bundle/ruby/2.3.0/gems/google-cloud-datastore-0.20.0/lib/google/cloud/datastore/service.rb:150:in `rescue in execute'
	from /home/deploy/apps/bilz-admin-app/shared/bundle/ruby/2.3.0/gems/google-cloud-datastore-0.20.0/lib/google/cloud/datastore/service.rb:146:in `execute'
	from /home/deploy/apps/bilz-admin-app/shared/bundle/ruby/2.3.0/gems/google-cloud-datastore-0.20.0/lib/google/cloud/datastore/service.rb:136:in `rollback'
	from /home/deploy/apps/bilz-admin-app/shared/bundle/ruby/2.3.0/gems/google-cloud-datastore-0.20.0/lib/google/cloud/datastore/transaction.rb:351:in `rollback'
	from /home/deploy/apps/bilz-admin-app/releases/20160831200427/app/models/concerns/datastore_syncable.rb:41:in `rescue in sync'
	from /home/deploy/apps/bilz-admin-app/releases/20160831200427/app/models/concerns/datastore_syncable.rb:30:in `sync'
	from /home/deploy/apps/bilz-admin-app/releases/20160831200427/app/models/post.rb:145:in `save_to_datastore'
```

<img width="1055" alt="screen shot 2016-08-31 at 1 48 38 pm" src="https://cloud.githubusercontent.com/assets/1023159/18145872/ea5347ce-6f81-11e6-9713-4e0ede33f01b.png">

<img width="768" alt="screen shot 2016-08-31 at 1 51 12 pm" src="https://cloud.githubusercontent.com/assets/1023159/18145905/0bba0592-6f82-11e6-884e-ed2c972f8b10.png">

**Comment by blowmage** [comment] 2016-08-31 21:07
A few more follow up questions:

1. Does this error happen all the time or intermittently?
2. Does this happen on both save and delete? Or does this happen on just one of those?
3. What is the error that is being rescued in the `sync` method?
4. Does this happen with 0.20.0?

**Comment by blowmage** [comment] 2016-08-31 21:09
Another follow up, I can recreate this error by trying to rollback a transaction that has already been committed:

```ruby
require "google/cloud"

gcloud = Google::Cloud.new
datastore = gcloud.datastore

tx = datastore.transaction
tx.commit
tx.rollback
#=> Google::Cloud::InvalidArgumentError: 3:The referenced transaction has expired or is no longer valid.
```

**Comment by whitmanc** [comment] 2016-08-31 21:23
1. All the time it seems, although the 1 time we tried to rescue the specific error, then it worked. Se  num 3 below
2. Save & delete both have the issue
3.  Strangely, when we did this before posting this ticket, the save worked and it didn't throw an error, and it was the only time it seemed to work. Going to follow up with more info, working on this with @emboss now
4. Happens with 0.20.0 as well, yes, tried upgrading to fix it and forgot to mention it

**Comment by emboss** [comment] 2016-08-31 23:54
@blowmage Thanks for taking care! I wasn't able to reproduce the original error, but I have found a very easy way to reproduce the original error that lead us on this path :)

After updating from `0.7.2`, we noticed that the application just hung itself up after calling `datastore.transaction`. No error, no timeout, it just hangs. This happens only on our staging server, but at least I was able to reproduce it locally.

If I open a Rails console and enter the following:

```ruby
ds = Gcloud.new("blitz-api-develop", "config/google-datastore.json").datastore
ds.transaction
```

Then it will hang itself up. If I CTRL+C, I get the following stacktrace:

```
IRB::Abort: abort then interrupt!
	from /home/martin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grpc-1.0.0-x86_64-linux/src/ruby/lib/grpc/generic/active_call.rb:80:in `run_batch'
	from /home/martin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grpc-1.0.0-x86_64-linux/src/ruby/lib/grpc/generic/active_call.rb:80:in `client_invoke'
	from /home/martin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grpc-1.0.0-x86_64-linux/src/ruby/lib/grpc/generic/active_call.rb:438:in `start_call'
	from /home/martin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grpc-1.0.0-x86_64-linux/src/ruby/lib/grpc/generic/active_call.rb:306:in `request_response'
	from /home/martin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grpc-1.0.0-x86_64-linux/src/ruby/lib/grpc/generic/client_stub.rb:167:in `request_response'
	from /home/martin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grpc-1.0.0-x86_64-linux/src/ruby/lib/grpc/generic/service.rb:184:in `block (3 levels) in rpc_stub_class'
	from /home/martin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/google-cloud-datastore-0.20.0/lib/google/cloud/datastore/service.rb:108:in `block in begin_transaction'
	from /home/martin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/google-cloud-datastore-0.20.0/lib/google/cloud/datastore/service.rb:147:in `block in execute'
	from /home/martin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/google-cloud-core-0.20.1/lib/google/cloud/core/grpc_backoff.rb:77:in `block in execute'
	from /home/martin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/google-cloud-core-0.20.1/lib/google/cloud/core/grpc_backoff.rb:75:in `loop'
	from /home/martin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/google-cloud-core-0.20.1/lib/google/cloud/core/grpc_backoff.rb:75:in `execute'
	from /home/martin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/google-cloud-datastore-0.20.0/lib/google/cloud/datastore/service.rb:146:in `execute'
	from /home/martin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/google-cloud-datastore-0.20.0/lib/google/cloud/datastore/service.rb:108:in `begin_transaction'
	from /home/martin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/google-cloud-datastore-0.20.0/lib/google/cloud/datastore/transaction.rb:250:in `start'
	from /home/martin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/google-cloud-datastore-0.20.0/lib/google/cloud/datastore/transaction.rb:66:in `initialize'
	from /home/martin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/google-cloud-datastore-0.20.0/lib/google/cloud/datastore/dataset.rb:450:in `new'
... 12 levels...
	from /home/martin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `load'
	from /home/martin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `block in load'
	from /home/martin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /home/martin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `load'
	from /home/martin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/commands/rails.rb:6:in `call'
	from /home/martin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/command_wrapper.rb:38:in `call'
	from /home/martin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/application.rb:191:in `block in serve'
	from /home/martin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/application.rb:161:in `fork'
	from /home/martin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/application.rb:161:in `serve'
	from /home/martin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/application.rb:131:in `block in run'
	from /home/martin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/application.rb:125:in `loop'
	from /home/martin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/application.rb:125:in `run'
	from /home/martin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /home/martin/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/martin/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

It's consistent with what I experience when I use byebug to step through the code. It hangs itself up in a `loop` in `ActiveCall#run_batch`. I tested this on `0.20.0`, Rails `5.0.0.1`, Ruby `2.3.1p112`.

The funny thing is now that the exact same code works fine when I run it from inside the application. On staging, we experience it the other way round: It hangs itself up when called from the application, but when I enter the lines above in the console, it will happily return the transaction.

If @chris tries the console code in his development environment, he will experience the same thing I do: Console hangs indefinitely, application works fine.

**Comment by blowmage** [comment] 2016-09-01 14:02
Hi @emboss, that actually sounds like a different problem than the one that this issue was opened for. There are some lingering issues running the GRPC client in a threaded environment line Puma. See #691 for more detail there. So far we have been unable to diagnose the problem, but there are several workarounds identified on that issue that seem to be working.

**Comment by whitmanc** [comment] 2016-09-01 14:14
@blowmage Happens on Apache as well.

**Comment by whitmanc** [comment] 2016-09-01 14:40
@blowmage is there any idea why the problem happens on one system (Ubuntu / Passenger)  but not another (OS X El Capitan / Puma)?

**Comment by blowmage** [comment] 2016-09-01 15:59
The problem in environments like Puma seems to be about the GRPC client in a forked process hanging. The original problem you opened this issue about seems to be different. It seems to me that you are calling rollback on a transaction object that is already committed. So the process isn't hung. I'd still really like to know what the error that your code is capturing is.

**Comment by whitmanc** [comment] 2016-09-01 17:23
@blowmage I wish I could help you help me more, haha. I feel like I'm not doing everything I can to aid you, but am not sure what else to provide... not getting any information other than what is posted unless I am missing something. 

I'd be happy to screen share and reproduce for you, but obviously wouldn't expect such support

Our current plan is to try one of the workarounds in #691, see if one of those works. If it does, great. Otherwise, we'll do the unthinkable and use a different gem version locally (el capitan/puma `0.20.0`) than on staging/production  (ubuntu/passenger, `0.7.2`)

By the way, thank you for all the help on the matter.

**Comment by bmclean** [comment] 2016-09-01 17:36
@whitmanc In your different systems (Ubuntu / Passenger / Apache) vs (OS X El Capitan / Puma) is Rails always running in production mode? Or is one of those running in development mode?

**Comment by whitmanc** [comment] 2016-09-01 17:38
@bmclean Rails is in development mode when running locally on El Capitan, staging mode when on Ubuntu

**Comment by bmclean** [comment] 2016-09-01 18:21
@whitmanc If your hanging problem is related to the GRPC forked process issue (#691), you might not see it when Rails is running in development mode. One difference between Rails development and production environments is that eager loading is enabled at boot for production environments. If the grpc library is initialized prior to the web server forking, the sub-processes don't have correct initialization. For example, require 'google/cloud/datastore' executed in a Rails initializer or in any code that is eager loaded (such as within the Rails app/ directory).

**Comment by blowmage** [comment] 2016-09-01 19:18
FWIW, I think that #875 may help with being able to use Google Cloud libraries from the main process before sub-processes are created.  PTAL

**Comment by whitmanc** [comment] 2016-09-01 21:56
@blowmage I'm trying your branch now. Locally first, then on the server. Meanwhile, @emboss is trying @bmclean's fix

Will follow up

**Comment by emboss** [comment] 2016-09-01 22:48
Thank you so much for your support guys. Great news, we were able to solve it!

We were using a singleton instance that was created in an initializer. Requiring `gcloud/datastore` and the datastore instance itself lazily as shown in #691 solved the issue for us. It's also working locally in the console now, no more problems here.

@blowmage For whatever reason I wasn't able to reproduce the original error anymore. We have tried so many combinations and settings, I lost track at some point - sorry. If we ever run into it again, I'll make sure to post it here! 

Again, great support, thanks everyone <3

**Comment by blowmage** [comment] 2016-09-01 23:29
@emboss Would it be possible to try the branch in #875 without the workaround in #691?

**Comment by whitmanc** [comment] 2016-09-02 00:46
@blowmage I will do it still, it's the least I could do since you've been so helpful. Will follow up, wrapping up other daily priorities and will swing back around to this

**Comment by whitmanc** [comment] 2016-09-02 02:51
@blowmage Your branch (#875) resolves the hanging issue locally and when deployed on the server. Hallelujah! cc @emboss @bmclean 

Thanks again everyone.

**Comment by blowmage** [comment] 2016-09-02 02:54
Okay, I'll get that merged and release some point releases tomorrow. Let me know when you get a reproduction on this issue.

**Comment by whitmanc** [comment] 2016-09-02 03:00
Sweeet! That's great news, we can reference the gem normally then once released. Will let you know if the error in the title comes up.

**Comment by quartzmo** [comment] 2016-09-07 21:34
Does the 0.20.1 release (with PR #875) resolve this issue?

**Comment by quartzmo** [comment] 2016-09-09 20:45
@whitmanc Can we close this issue?

**Comment by quartzmo** [comment] 2016-09-13 16:42
Closing. @whitmanc Please reopen if you experience this issue again while using the 0.20.1 release.

**Closed by quartzmo** 2016-09-13 16:42 UTC
Labels: datastore, grpc, question

**Comment by whitmanc** [comment] 2016-09-21 17:21
@quartzmo missed these notifications, all good for closing, issue is resolved.

**Comment by quartzmo** [comment] 2016-09-21 17:25
Great, thanks @whitmanc.
