### ISSUE TITLE
Display the content for GAPIC/GRPC API version such as 'V1' menu item

### ISSUE THREAD

**Issue by swcloud** [GoogleCloudPlatform/google-cloud-ruby#1181] opened 2017-01-05 18:18 UTC
Right now, if a user clicks 'V1' menu item on the left navigation panel, the right side displays an empty page. We should add content for this menu item or find a way to not change the content on the right side when the menu item is clicked, i.e., when a user clicks 'V1', what it only does is to expand the sub menu items.

**Comment by quartzmo** [comment] 2017-01-05 18:39
Currently, when any left nav item is clicked, related content is shown in the main page. Clicking any of the top-level "service" nav items ('BigQuery', 'Datastore', etc) results in the display of an overview discussion of the service. Example:

https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.23.0/google/cloud/datastore

> Google Cloud Datastore is a fully managed, schemaless database for storing non-relational data. You should feel at home if you are familiar with relational databases, but there are some key differences to be aware of to make the most of using Datastore.

I think for consistency we should stick to this pattern. Clicking the 'V1' should display an overview discussion informing the user about purpose and expected usage of the GAPIC API.

**Comment by danoscarmike** [comment] 2017-02-23 18:52
@omaray to flesh out design.  At minimum we need to provide content / redirect.

**Comment by geigerj** [comment] 2017-06-01 22:21
@landrito Let's put the README content in the version landing page in the meantime.

**Comment by danoscarmike** [comment] 2017-06-27 19:37
@landrito @geigerj can you please revisit?  Is priority P0 appropriate here - critical issue / imminent release blocking?  Thanks.

**Comment by landrito** [comment] 2017-06-27 19:39
I think this can be resolved. @eoogbe made this https://github.com/googleapis/toolkit/pull/1358 which should address this. @geigerj @eoogbe can you confirm?

**Comment by geigerj** [comment] 2017-06-27 19:46
@danoscarmike This is blocking for all new beta-level releases. I'm not clear on the distinction between P0 and P1 that we're using. As @landrito said, @eoogbe is actively working on this.

**Comment by danoscarmike** [comment] 2017-06-28 03:55
@swcloud can you please verify and close this issue if resolved?  Thanks!

**Comment by geigerj** [comment] 2017-06-28 15:40
@danoscarmike this issue is not resolved; there is still WIP. It's not blocking _any_ imminent releases, but it is blocking _beta_ releases. I think P0 is probably still accurate.

**Comment by danoscarmike** [comment] 2017-06-28 16:09
Understood.  Thanks @geigerj

**Comment by geigerj** [comment] 2017-08-09 23:31
@landrito temporarily assigning this to you, as this will be resolved by the global GAPIC refresh you are working on in `api-client-staging` currently. When the `api-client-staging` refresh is done, we'll need to create PRs to this repo and push the documentation updates. You can either do that or reassign to me to do so once the CI passes on `api-client-staging`.

**Comment by danoscarmike** [comment] 2017-08-31 03:37
Ping. @landrito @geigerj can you please update the status of this one?

**Comment by geigerj** [comment] 2017-08-31 14:05
I will regenerate monitoring today, and once that's pushed to the github.io site we can verify the fixes that we made in the generator.

**Comment by quartzmo** [comment] 2017-09-01 23:34
In Video Intelligence, there is now content configured from the `V1Beta2` module for the link/page of this name. However, it is [not showing up](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-video_intelligence/master/google/cloud/videointelligence/v1beta2). I think this may be due to a limitation in our `gcloud-jsondoc` tool, which I believe only generates documentation from classes, not modules. I'll look into this and confirm.

**Comment by geigerj** [comment] 2017-09-05 17:34
@quartzmo Once you have a better idea of what the limitation is, could you give me a sense of the approximate cost of changing the tool to support module-level documentation? Also, whether there's some other approach we can take with the code generator to feed these docs to the `gcloud-jsondoc` tool -- can we write this to a text file and feed it through the the `jsondoc` Rake task?

**Comment by quartzmo** [comment] 2017-09-06 23:02
> could you give me a sense of the approximate cost of changing the tool...

I spent most of today working on it, but I did not yet find a solution. So I can only guess that it will take another day, or two.

> whether there's some other approach we can take with the code generator to feed these docs to the `gcloud-jsondoc` tool 

I have a feeling this might be easier. If I get any ideas I won't hesitate to run them by you here on this issue.

**Comment by geigerj** [comment] 2017-09-06 23:06
Thanks, @quartzmo.

**Comment by quartzmo** [comment] 2017-09-07 17:33
@geigerj Will it work with the generator to move these top-level docs to a declaration of the module that is in a `doc` directory? In the case of Video Intelligence `V1Beta2`, this would be from [`lib/google/cloud/video_intelligence/v1beta2.rb#L51-L62`](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/google-cloud-video_intelligence/v0.22.0/google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta2.rb#L51-L62) to [`lib/google/cloud/video_intelligence/v1beta2/doc/google/cloud/videointelligence/v1beta2/video_intelligence.rb#L18`](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/google-cloud-video_intelligence/v0.22.0/google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta2/doc/google/cloud/videointelligence/v1beta2/video_intelligence.rb#L18).

**Comment by geigerj** [comment] 2017-09-07 17:45
@quartzmo Sure, we can try that. (It's slightly complicated from the generator side because there is not always a module in the `doc/` directory currently that corresponds to the API client module, e.g., for any API that doesn't have a `cloud` package in its proto namespace. But we can generate a new file in those cases.)

Before I start making the change to the generator, were you able to confirm that this will work when you make the change manually?

**Comment by quartzmo** [comment] 2017-09-07 17:58
Yes, it works for me locally after changing the `gcloud-jsondoc` tool to include modules as well as classes.

FYI, the left nav item [can be mapped to any jsondoc output](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/google-cloud-video_intelligence/v0.22.0/google-cloud-video_intelligence/docs/toc.json#L26). The problem is that the YARD objects used to generate these outputs do not correspond to files, and for some reason I could not find any documentation output from the `V1beta2` module docs in the existing location outside of `doc/`, even though the file seemed to be in the path. (It is not excluded in `.yardopts`.) I can keep trying to debug it if it seems better to you than moving the docs.

**Comment by geigerj** [comment] 2017-09-07 18:26
Thanks for looking into this, @quartzmo.

@eoogbe is going to make the change in the code generator. We expect to have an update early next week.

**Comment by quartzmo** [comment] 2017-09-07 18:30
OK, I'll push the change to the gcloud-jsondoc tool to include modules as well as classes now.

**Comment by quartzmo** [comment] 2017-09-14 23:29
@geigerj 

I was just alerted to an issue in the page that was generated following #1714 by @blowmage: On the [Google::Cloud::VideoIntelligence::V1beta2](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-video_intelligence/master/google/cloud/videointelligence/v1beta2) page, the two links in the table are broken.

I'm not sure of the root cause, but I noticed that the broken links have a repeated `v1beta2` directory: `../v1beta2/v1beta2/..`

Correct:

`https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-video_intelligence/master/google/cloud/videointelligence/v1beta2/videointelligenceserviceclient`

Broken:

`https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-video_intelligence/latest/google/cloud/videointelligence/v1beta2/v1beta2/videointelligenceserviceclient`

**Comment by geigerj** [comment] 2017-09-14 23:39
@eoogbe This looks an issue with the `toolkit` template that's generating [these lines](https://github.com/GoogleCloudPlatform/google-cloud-ruby/pull/1714/files#diff-0ddd7effd5b90c3e650f047087da1903R26). Could you take a look?

**Comment by eoogbe** [comment] 2017-09-14 23:57
@geigerj It looks like it's [this line](https://github.com/googleapis/toolkit/blob/master/src/main/java/com/google/api/codegen/transformer/ruby/RubyPackageMetadataTransformer.java#L144) that's causing the problem. It's based on the brittle [`proto_path`](https://github.com/googleapis/artman/blob/80decc01a66325dbefbc7ca6a943feb489c4956e/artman/tasks/package_metadata_tasks.py#L90) property which varies based on the common directory of all the src protos. The tests set the value explicitly which is probably why we didn't catch it. We need to either generate the url with a less brittle property or make the property itself easier to predict.

**Comment by geigerj** [comment] 2017-09-15 00:03
@eoogbe Agreed. Suggest that instead of using `proto_path` from the PackageMetadata we should instead use the package declared for the `.proto` file that contains the `service` being documented. This should contain the version already, so there will be no need to append the version explicitly in `RubyPackageMetadataTransformer.generateTocContent()`.

**Comment by eoogbe** [comment] 2017-09-15 00:54
How do I access the file path from the ProtoFile object?

**Comment by geigerj** [comment] 2017-09-15 03:13
@eoogbe For the package, you want `protoFile.getProto().getPackage()`.

**Comment by geigerj** [comment] 2017-09-15 17:38
From @blowmage on #1714:

> K, FWIW I think those links will be problematic because they always go to the latest release. If you are looking at a previous release (or master) and click those links they will jump you to latest. That might be frustrating for users who aren't expecting it to change the version they are looking at.

@eoogbe we should also switch to use a relative link here to avoid the issue @blowmage raises.

**Comment by eoogbe** [comment] 2017-09-15 21:37
What does a correct relative link look like? For example, if this is the absolute:
`https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-video_intelligence/latest/google/cloud/videointelligence/v1beta2/videointelligenceserviceclient`

**Comment by geigerj** [comment] 2018-01-17 00:03
https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-video_intelligence/v1.0.0/google/cloud/videointelligence/v1 now shows a table of contents. Closing this issue.

**Closed by geigerj** 2018-01-17 00:03 UTC
Labels: api: core, api: video intelligence, documentation, gapic, priority: p2, release blocking, status: acknowledged, type: cleanup
