### ISSUE TITLE
Memory leak with datastore using grpc version 1.2.2

### ISSUE THREAD

**Issue by bmclean** [GoogleCloudPlatform/google-cloud-ruby#1421] opened 2017-04-12 22:43 UTC
During a recent bundle update of our app the version of `grpc` changed from 1.2.0 to 1.2.2. With the new version of `grpc` I am seeing runaway memory use. Here is a screenshot from a test I ran on Heroku. The initial flat spot is the Rails app running happily after deploy and the start of the large ramp was caused by a single datastore query. I then left the app alone and didn't make any more requests. Memory use continued to climb until 8:10am when Heroku killed the dyno. The app restarted and once again ran happily until I made another datastore request at 11:30 am and the ramp started over. The deploy of v 223 was with a single change of `gem 'grpc', '1.2.0'` to the Gemfile and the app has been running happily since.

<img width="1320" alt="memory" src="https://cloud.githubusercontent.com/assets/622145/24982082/dc314864-1f9c-11e7-993f-385efc80146e.png">

I can also reproduce this locally using the `derailed` [gem](https://github.com/schneems/derailed). Has anything changed with version 1.2.2 of the `grpc` gem that needs a change to the datastore code? Or should this issue be moved to the grpc repo?

**Comment by blowmage** [comment] 2017-04-12 22:55
@bmclean Thanks for opening the issue.

@swcloud Can we get someone from the grpc team to look at this?

**Comment by bmclean** [comment] 2017-04-14 20:58
Might be related: https://github.com/grpc/grpc/issues/10658

**Comment by bmclean** [comment] 2017-04-14 21:06
The `require grpc` would be happening when the first datastore query occurs (shown above).

**Comment by swcloud** [comment] 2017-04-14 23:41
Adding @apolcyn

**Comment by apolcyn** [comment] 2017-04-14 23:53
I do think this is running into the same issue as in https://github.com/grpc/grpc/issues/10658.

If at all there is a fork after a 'require grpc', with grpc version 1.2.2, then unfortunately I'd expect these issues right now.  There is a background thread in 1.2.2 involved in grpc channel lifecycles, and after a fork, if it's not there in the child process, then garbage collection of grpc channels will start to fail.

**Comment by apolcyn** [comment] 2017-04-15 00:00
^ comment above is still a guess of what the app here is doing though, I'm not certain this is the same as in grpc/grpc#10658

**Comment by bmclean** [comment] 2017-04-15 00:40
I am not certain either. The Rails app used in the Heroku test was using Puma configured with 1 worker and 5 threads. So it could not have forked another process. The ruby client delays loading grpc until it is used (see [here](https://github.com/GoogleCloudPlatform/google-cloud-ruby/pull/875)) and the memory starts ramping up immediately after the first datastore query (when grpc was loaded).

**Comment by bmclean** [comment] 2017-04-15 04:22
I have created a simplified Rails 5 app that uses the `derailed` gem to show the memory usage. It uses an actual cloud datastore instance (so needs a project ID), authenticated locally through gcloud auth login. Clone the grpc-1.2.2-memory branch from [here](https://github.com/Agrimatics/activemodel-datastore/tree/grpc-1.2.2-memory). Note that when running derailed to profile the memory usage all tests are run without a webserver, as it uses Rack directly. The Rails app is set to use grpc 1.2.0 initially.

`cd test/support/datastore_example_rails_app`
`bundle`

Check if the app is connecting to datastore by running:

`RAILS_ENV=production GCLOUD_PROJECT=project-id-goes-here rails server`

Navigate to localhost:3000 with a browser and create a few users.
Execute the following command to run the derailed benchmark (substitute your datastore project ID).

`DERAILED_SKIP_ACTIVE_RECORD=true PATH_TO_HIT=/users GCLOUD_PROJECT=project-id-goes-here TEST_COUNT=5000 bundle exec derailed exec perf:mem_over_time`

The profile will take about 15 minutes.
Then change the version of grpc to 1.2.2 in the Gemfile.

`bundle update`

Run the derailed command again to compare.

**Comment by bmclean** [comment] 2017-04-15 04:25
You should end up with something that looks like this:

<img width="661" alt="graph" src="https://cloud.githubusercontent.com/assets/622145/25060704/39df1d0e-2161-11e7-95aa-0d88db79ca19.png">

**Comment by apolcyn** [comment] 2017-04-15 07:16
Inconclusive yet but looking into this and seem to be getting similar results. Thanks for the repro, this is really helpful!

**Comment by apolcyn** [comment] 2017-04-17 19:38
@bmclean to be certain about the initial problem, you noticed runaway memory usage after only one datastore call? I'm not sure exactly which query it was, do we know if this translates to only one grpc call?

I'm seeing similar results with the benchmark memory comparisons in the graph above, but I'm not sure if these differences are necessarily hitting the bug in the original issue (trying reproduce that).

**Comment by bmclean** [comment] 2017-04-17 21:54
@apolcyn Correct. An ancestor query with an equality filter on one property:
```
query = CloudDatastore.dataset.query  'User'
query.ancestor(ancestor_key)
query.where('disabled', '=', false)
entities = CloudDatastore.dataset.run query
```
You have a valid point that the memory benchmark isn't exactly the same. It is performing the query repeatedly. I didn't see a way for derailed to hit the url only once but keep monitoring the memory.

So, I have added displaying the memory of the process to the example app. The index page of the app does not perform any queries. Start at the index page, then click to view the users (which performs a query) and then go back to the index page. Refresh the index page every few minutes and with 1.2.0 the memory eventually stays constant but with 1.2.2 it keeps climbing.

**Comment by bmclean** [comment] 2017-04-17 21:56
You can start the Rails server locally with `RAILS_ENV=production GCLOUD_PROJECT=project-id-goes-here rails server`

**Comment by apolcyn** [comment] 2017-04-18 07:16
So it looks like this is definitely a pure grpc problem, it can actually be reproduced easily with a grpc example tweaked to:

```
  def main
    stub = Helloworld::Greeter::Stub.new('localhost:50051', :this_channel_is_insecure)
    user = ARGV.size > 0 ?  ARGV[0] : 'world'
    message = stub.say_hello(Helloworld::HelloRequest.new(name: user)).message
    p "Greeting: #{message}"
  
    loop do
      sleep 30
      p "#{(`ps -o rss= -p #{Process.pid}`.to_i * 1024).to_f / 2**20}"
    end
  
    stub.inspect
  end
  
  main
```

(it looks like the background thread that was added in v1.2.x to keep fix connectivity-related failures seems to be accumulating a lot of more memory - it makes a check on a timer, and memory accumulates proportionally to the speed of it  e.g., setting https://github.com/grpc/grpc/blob/master/src/ruby/ext/grpc/rb_channel.c#L425 to a lower value can cause almost all of heap allocs to be from within `grpc_channel_watch_connectivity_state`)

**Comment by bmclean** [comment] 2017-04-18 17:28
Thanks @apolcyn!

**Comment by apolcyn** [comment] 2017-04-19 00:09
A heads up that the fix for this is under WIP but isn't immediate.

**Comment by apolcyn** [comment] 2017-04-20 05:44
In the meantime, going to release a 1.2.5 gem that reverts the connectivity fix (in https://github.com/grpc/grpc/pull/9986), which is causing this issue.

**Comment by bmclean** [comment] 2017-05-24 22:06
@apolcyn I deployed `grpc` version 1.3.4 to our staging environment today and so far everything looks fine.

**Comment by bmclean** [comment] 2017-05-25 21:53
24 hours later and memory is still holding steady. Nice work @apolcyn! Are we ok to close this issue?

**Comment by blowmage** [comment] 2017-05-25 22:16
Great news @bmclean! Feel free to close this issue if you feel it is resolved.

**Closed** 2017-05-25 22:21 UTC
Labels: Priority: P1, Status: Acknowledged, triaged, Type: Bug

**Comment by apolcyn** [comment] 2017-05-26 04:12
thanks for updates @bmclean, glad to hear that you're seeing the issue fixed!
