### ISSUE TITLE
Error "SignatureDoesNotMatch". Google Cloud Storage Bucket PUT.

### ISSUE THREAD

**Issue by johnunclesam** [GoogleCloudPlatform/google-cloud-ruby#1964] opened 2018-02-12 02:13 UTC
I'm loosing my mind.

I'm using Shrine (https://github.com/janko-m/shrine) with Google Cloud Storage (https://github.com/renchap/shrine-google_cloud_storage), but when I start the `PUT` call I get this:

```
<Error>
<Code>SignatureDoesNotMatch</Code>
<Message>
The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method.
</Message>
<StringToSign>
PUT
image/jpeg
1518399402
/mybucket.appspot.com/7d5e4aad1e3a737fb8d2c59571fdb980.jpg
</StringToSign>
</Error>
```

I followed this info (http://shrinerb.com/rdoc/classes/Shrine/Plugins/PresignEndpoint.html) for `presign_endpoint`, but still nothing:

```ruby
class FileUploader < Shrine
  plugin :presign_endpoint, presign_options: -> (request) do
    filename     = request.params["filename"]
    extension    = File.extname(filename)
    content_type = Rack::Mime.mime_type(extension)

    {
      content_type: content_type
    }
  end
end
```

**I tried with and without this** (restarting the Rails server everytime).

Where am I wrong?

I also tried with Postman with a PUT to that URL and withtout any **content-type**. But still nothing.

I read here: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1976 and here: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1695

How can I try without Rails?

Is there a REPL (or similar) to try with my credentials and with a file?

**Comment by quartzmo** [comment] 2018-02-12 17:16
Hi @johnunclesam,

Can you try the operation in IRB directly with [google-cloud-storage](https://github.com/GoogleCloudPlatform/google-cloud-ruby/tree/master/google-cloud-storage). You can provide your credentials in code as shown in [the guide](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-storage/latest/google/cloud/storage).

**Comment by johnunclesam** [comment] 2018-02-12 17:34
@quartzmo I'm sorry, I'm trying to understand if the problem is here: https://github.com/renchap/shrine-google_cloud_storage/issues/22 or here: https://github.com/janko-m/shrine/issues/250.

**Comment by quartzmo** [comment] 2018-02-12 18:14
I'll take a look at renchap/shrine-google_cloud_storage#22 to see if I can help.

**Comment by johnunclesam** [comment] 2018-02-12 18:16
@quartzmo but maybe the problem is here: https://github.com/janko-m/shrine/blob/master/lib/shrine/plugins/presign_endpoint.rb

**Comment by quartzmo** [comment] 2018-02-12 22:43
I read through the linked issues and Shrine code/docs today but couldn't debug the issue. I agree that it seems the problem is likely to be related to the usage or configuration of the Shrine `PresignEndpoint` plugin. I'm going to close this issue since I currently see no evidence that the issue is in google-cloud-storage. Please re-open if you can isolate the problem to google-cloud-storage, otherwise I think renchap/shrine-google_cloud_storage#22 is the correct issue to track this problem.

**Closed by quartzmo** 2018-02-12 22:43 UTC
Labels: api: storage, priority: p2, type: bug

**Comment by janko-m** [comment] 2018-02-12 23:56
@quartzmo I managed to isolate the issue. 

```rb
require "google/cloud/storage"
require "http" # gem install http

storage = Google::Cloud::Storage.new(
  project_id: "...",
  credentials: "/path/to/credentials.json",
)

bucket = storage.create_bucket("my-bucket-#{SecureRandom.hex}")

upload_url = storage.signed_url(bucket.name, "file.txt", method: "PUT", expires: 60 * 5, content_type: "text/plain")

p HTTP.put(upload_url, body: "content").to_s
# => "<?xml version='1.0' encoding='UTF-8'?><Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method.</Message><StringToSign>PUT\n\n\n1518479990\n/my-bucket-e3b6f41392edd7c5930cf6faac638ddc/file.txt</StringToSign></Error>"

bucket.delete
```

Note that if I remove the `:content_type` option, the upload succeeds.

**Comment by johnunclesam** [comment] 2018-02-13 00:00
@janko-m thanks for this discovery.

**Comment by janko-m** [comment] 2018-02-13 00:07
@johnunclesam I just found the documentation for the `:content_type` option:

<img width="751" alt="screen shot 2018-02-13 at 01 03 38" src="https://user-images.githubusercontent.com/795488/36126656-c3eaa59e-1059-11e8-81f2-9858793b65af.png">

It seems that the problem is that the PUT request needs to include the `Content-Type: text/plain` header. When I change

```rb
HTTP.put(upload_url, body: "content")
``` 

to

```rb
HTTP.headers("Content-Type" => "text/plain").put(upload_url, body: "content")
```

the upload works. This means there is no problem with the google-cloud-storage gem, because the `Content-Type` request header requirement is documented.

**Comment by quartzmo** [comment] 2018-02-13 00:35
@janko-m Thank you for clarifying this. How does this behavior in google-cloud-storage relate to the [problem with the PresignEndpoint configuration](https://github.com/renchap/shrine-google_cloud_storage/issues/22#issuecomment-364994262)? (Feel free to answer in that issue and link back from here.)

**Comment by janko-m** [comment] 2018-02-13 00:49
@quartzmo Shrine's presign endpoint returns URL, fields and headers that the client (browser) needs to upload to. The `Shrine::Storage::GoogleCloudStorage#presign` method, which the presign endpoint calls, never returns any headers, which means that the presign endpoint always returns `"headers": {}` in the response. When the browser then tries to upload the file to the URL, but because the request headers required by GCS weren't included, the upload fails.

The solution is for `Shrine::Storage::GoogleCloudStorage#presign` to return appropriate headers when either `:content_type`, `content_md5` or `headers` options were given, which will make the presign endpoint automatically return them, and then the client (browser) can then include them in the upload request. I'm currently working on this PR.

**Comment by quartzmo** [comment] 2018-02-13 02:14
@janko-m Thank you for this clear explanation and for the PR. If we can ever do anything to facilitate integration with Shrine, please immediately open an issue here to discuss. We really appreciate your efforts to support and include Google Cloud Storage.
