### ISSUE TITLE
Page not found in Ruby Docs

### ISSUE THREAD

**Issue by frankyn** [GoogleCloudPlatform/google-cloud-ruby#965] opened 2016-10-11 17:10 UTC
Issue: 
Source links in [Ruby API documentation](http://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.20.1/google/cloud) are broken. 

Example:
If you go to the [Ruby API documentation](http://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.20.1/google/cloud) and click on any **Source Code** link it will 404.

**Comment by quartzmo** [comment] 2016-10-13 22:20
@frankyn Thank you for taking the time to report this. I am closing it as a dupe of #908, which I reopened. (#908 captures some discussion on the cause and solution; in case there is any more, I want to keep it in that issue.)

Please never hesitate to open an issue when you see something that can be improved in the docs (or the libraries.) Much appreciated!

**Closed by quartzmo** 2016-10-13 22:20 UTC
Labels: bug, docs, dupe

**Comment by frankyn** [comment] 2016-10-13 23:06
Thanks @quartzmo!
