### ISSUE TITLE
Stackdriver Trace not working locally

### ISSUE THREAD

**Issue by bshaffer** [GoogleCloudPlatform/google-cloud-ruby#2013] opened 2018-03-21 00:09 UTC
I followed [the setup instructions](https://cloud.google.com/trace/docs/setup/ruby) for Rails: 

  1. added `gem "stackdriver"` and 
  1. I ran `bundle install`
  1. added `require "google/cloud/trace/rails"` to `application.rb`
  1. set the environment variable `GOOGLE_PROJECT_ID` (and `GCLOUD_PROJECT_ID` and `GOOGLE_CLOUD_PROJECT` to be safe)
  1. set the environment variable`GOOGLE_APPLICATION_CREDENTIALS` 
  1. ran `bundle exec rails server`

No traces were ever recorded in the UI. I manually set values for `config.google_cloud.trace.project_id` and `config.google_cloud.trace.keyfile` in `config/environments/development.rb` and still did not see traces. 

So far I cannot find a way to log traces in a local development environment!

**Comment by blowmage** [comment] 2018-03-21 01:14
@dazuma Can you weigh in on this?

**Comment by blowmage** [comment] 2018-03-21 01:20
@bshaffer Are you setting the `use_trace` configuration to `true`? My (limited) understanding is that Trace is not enabled by default unless Rails is running in production, but you can override this using that setting. See the [Stackdriver Configuration guide](http://googlecloudplatform.github.io/google-cloud-ruby/#/docs/stackdriver/v0.14.0/guides/instrumentation_configuration) for more.

**Comment by bshaffer** [comment] 2018-03-21 17:01
Ahh, then this is more of an issue for the [setup instructions](https://cloud.google.com/trace/docs/setup/ruby), as there is no mention of `use_trace` on there.

**Comment by thagomizer** [comment] 2018-03-21 17:18
@bshaffer @blowmage I've tried testing locally both with just `bundle exec rails s` and `RAILS_ENV=production bundle exec rails s` and I'm still not seeing traces. And I'm getting an error in the trace background task.

**Comment by blowmage** [comment] 2018-03-21 17:37
I haven't worked on any of the Stackdriver gems except for Logging. @dazuma, what can you tell us about this?

**Comment by thagomizer** [comment] 2018-03-22 22:24
Error:

Google::Cloud::PermissionDeniedError: 7:The caller does not have permission
	/Users/ajahammerly/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/google-cloud-trace-0.27.2/lib/google/cloud/trace/service.rb:161:in `rescue in execute'
	/Users/ajahammerly/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/google-cloud-trace-0.27.2/lib/google/cloud/trace/service.rb:158:in `execute'
	/Users/ajahammerly/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/google-cloud-trace-0.27.2/lib/google/cloud/trace/service.rb:98:in `patch_traces'
	/Users/ajahammerly/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/google-cloud-trace-0.27.2/lib/google/cloud/trace/async_reporter.rb:79:in `run_backgrounder'
	/Users/ajahammerly/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/stackdriver-core-1.2.0/lib/stackdriver/core/async_actor.rb:291:in `async_run_job'
	/Users/ajahammerly/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/stackdriver-core-1.2.0/lib/stackdriver/core/async_actor.rb:315:in `block (2 levels) in ensure_thread'

**Comment by blowmage** [comment] 2018-03-22 23:03
@thagomizer Can you verify the Trace service has been enabled on your account?

**Comment by premist** [comment] 2018-03-27 13:24
@thagomizer 

You will need to enable Cloud Trace Agent (roles/cloudtrace.agent) IAM role as described in [this document](https://cloud.google.com/trace/docs/iam#roles). 

Also, when you're running code on non-GCP environment (such as your local laptop), you need to be subscribed to [Stackdriver Premium Tier](https://cloud.google.com/stackdriver/pricing#service_tiers) to get Trace working. I was scratching my head since there was no error being logged on my machine but I couldn't get it to work, but the problem disappeared after I sign up for Premium Tier. Looks like Premium Tier's 'GCP and AWS' means 'GCP and other infrastructure'. 

Note that Stackdriver pricing will change this year, so I assume you don't have to be in the Premium Tier to use Cloud Trace on your local computer [starting September 30, 2018](https://cloud.google.com/stackdriver/pricing_v2#trace-costs).

**Comment by blowmage** [comment] 2018-03-29 16:06
@bshaffer Has your question been answered satisfactorily? Can this issue be closed?

**Comment by dazuma** [comment] 2018-05-08 22:03
I confirmed with a new project that the `use_trace` setting needs to be covered (good catch @blowmage), but otherwise the steps work as is. I'll close this and open an internal issue to fix the documentation page.

**Closed by dazuma** 2018-05-08 22:03 UTC
Labels: api: trace, type: question
