### ISSUE TITLE
[stackdriver] API enabled, but stackdriver not working, suspicious errors in logs

### ISSUE THREAD

**Issue by samkelly** [GoogleCloudPlatform/google-cloud-ruby#1355] opened 2017-03-24 02:18 UTC
my rails GAE application is throwing errors (I can see them in the logs), but they are not getting logged in stackdriver. I use the stackdriver gem, and I have all stackdriver-related APIs enabled. I am seeing this log entry whenever an error occurs:

```
14:02:06.515
Transmit to Stackdriver Trace failed: #<Google::Cloud::InternalError: 13:{"created":"@1490292126.514668478","description":"Transport closed","file":"src/core/ext/transport/chttp2/transport/chttp2_transport.c","file_line":1072}>
 {
 textPayload: "Transmit to Stackdriver Trace failed: #<Google::Cloud::InternalError: 13:{"created":"@1490292126.514668478","description":"Transport closed","file":"src/core/ext/transport/chttp2/transport/chttp2_transport.c","file_line":1072}>"   
 insertId: "7hr66nfrepuyy"   
 resource: {…}   
 timestamp: "2017-03-23T18:02:06.515444151Z"   
 severity: "ERROR"   
 logName: "projects/redacted/logs/ruby_app_log"   
}
```

edit: actually I am seeing the above error intermittently -- when a ruby error occurs, there doesn't seem to be anything related to stack driver that is complaining, which is even more annoying.

**Comment by samkelly** [comment] 2017-03-24 02:29
this one does appear in stackdriver every once in a while, but I have no idea what it means (no error name or description, just this):

```
19:30:18.724
vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/debug_exceptions.rb:53:in `call' vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call' vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/rack/logger.rb:36:in `call_app' vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/rack/logger.rb:26:in `call' vendor/bundle/ruby/2.3.0/gems/google-cloud-logging-0.24.2/lib/google/cloud/logging/middleware.rb:70:in `call' vendor/bundle/ruby/2.3.0/gems/request_store-1.3.2/lib/request_store/middleware.rb:9:in `call' vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/request_id.rb:24:in `call' vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/method_override.rb:22:in `call' vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/runtime.rb:22:in `call' vendor/bundle/ruby/2.3.0/gems/google-cloud-trace-0.23.2/lib/google/cloud/trace/middleware.rb:154:in `block in call' vendor/bundle/ruby/2.3.0/gems/google-cloud-trace-0.23.2/lib/google/cloud/trace.rb:329:in `block in in_span' vendor/bundle/ruby/2.3.0/gems/google-cloud-trace-0.23.2/lib/google/cloud/trace/trace_record.rb:229:in `in_span' vendor/bundle/ruby/2.3.0/gems/google-cloud-trace-0.23.2/lib/google/cloud/trace.rb:326:in `in_span' vendor/bundle/ruby/2.3.0/gems/google-cloud-trace-0.23.2/lib/google/cloud/trace/middleware.rb:152:in `call' vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call' vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/executor.rb:12:in `call' vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/static.rb:136:in `call' vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/sendfile.rb:111:in `call' vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/engine.rb:522:in `call' vendor/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/configuration.rb:224:in `call' vendor/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/server.rb:600:in `handle_request' vendor/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/server.rb:435:in `process_client' vendor/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/server.rb:299:in `block in run' vendor/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

**Comment by remi** [comment] 2017-03-24 07:28
/cc @hxiong388 @dazuma 

Hey Sam, thanks for the report!  Looks like Trace is blowing up, for sure (*from both of your posted errors*).

I wonder if the Stackdriver Error Reporting and Logging integrations are working for you?  If you visit [Error Reporting](https://console.cloud.google.com/errors) in the Console, do you see any errors reported?

![Example of Error Reporting](http://i.imgur.com/FCPNjdK.png)

Also, if Stackdriver Logging is working, the log entries you see in the [Logs Viewer](https://console.cloud.google.com/logs/viewer) should show your logs with associated severity.

![Example of Logs Viewer](http://i.imgur.com/6J4RdUr.png)

To try to reproduce, I deployed a fresh Rails 5.0.2 application on Ruby 2.3.0 to App Engine (*based on your error output*) with `gem "stackdriver"` added.  I enabled the *Stackdriver Logging API*, *Stackdriver Error Reporting API*, and *Stackdriver Trace API* APIs.  Stackdriver Logging, Error Reporting, and Trace worked for me, so I'm pinging one of our engineers...

I /cc'd someone to look into that Trace error!  Let us know if there's any other information that might help us debug in the meantime.

**Comment by dazuma** [comment] 2017-03-31 01:33
@apolcyn Can you shed any light on this error (happening on the client side during send)?
```
Google::Cloud::InternalError: 13:{"created":"@1490292126.514668478","description":"Transport closed","file":"src/core/ext/transport/chttp2/transport/chttp2_transport.c","file_line":1072}
```
Is this due to a network issue or an internal state out of sync?

**Comment by swcloud** [comment] 2017-03-31 01:37
@samkelly This is the same error reported from #899 

grpc-1.2.1.pre1 pre-release gem has a work-around. Please give it a try

**Comment by apolcyn** [comment] 2017-03-31 01:55
@dazuma @swcloud yeah this looks like the same issue as in #899.

The problem this looks like is a problem in the grpc gem, happening when a "grpc client stub" of "grpc client channel" is inactive while the connection breaks, and then a new call is made on it.

As noted there a fix for this was made in grpc-1.2.1.pre1

(the cause is that in grpc-ruby < 1.2.1.pre1, the grpc "c-core" library doesn't get called into while there's no activity, and it doesn't notice that it lost its connection until a new call has been made, at which point it just fails the call instead of reconnecting).

**Comment by swcloud** [comment] 2017-04-11 21:33
@samkelly Does grpc-1.2.2 fix this issue for you?

**Comment by samkelly** [comment] 2017-04-11 21:41
I will try updating and let you know. If you don't hear from me, it worked!

**Comment by swcloud** [comment] 2017-04-14 23:39
I assume it's working and close this issue.

**Closed by swcloud** 2017-04-14 23:39 UTC
Labels: Priority: P2+, stackdriver, Status: Acknowledged
