### ISSUE TITLE
Pubsub: Doesn't work subscriber in Rails

### ISSUE THREAD

**Issue by mackeee-orange** [GoogleCloudPlatform/google-cloud-ruby#1940] opened 2018-01-22 11:00 UTC
I'm using GCP Pubsub in Rails application. Environment:
```
Rails: v5.1.4
Ruby: v2.4.2
google-cloud-pubsub: v0.29.0
MacOS: 10.12.6 Sierra
```
this is code:

```
require 'json'
require 'google/cloud/pubsub'

module ActiveJob
  module QueueAdapters
    class PubSubQueueAdapter

      def enqueue(job)
        Rails.logger.info "[PubSubQueueAdapter enqueue job #{job.inspect}"

        topic = PubSubQueueAdapter.pubsub.topic(job.queue_name)
        topic.publish(job.class.name, arg: job.arguments)
      end

      class << self
        def pubsub
          @pubsub ||= begin
            project_id = Rails.application.config.x.settings['project_id']
            Google::Cloud::Pubsub.new(
                project_id: project_id,
                credentials: "#{Rails.root.join('config')}/#{Rails.application.config.x.settings['auth_file']}"
            )
          end
        end

        def run_worker!(queue_name = 'default')
          p 'Running worker'
          topic = pubsub.topic(queue_name)
          sub = topic.subscription("#{queue_name}_task") || topic.subscribe("#{queue_name}_task")
          subscriber = sub.listen threads: { callback: 16 } do |message|
            p message
            message.acknowledge!
          end

          subscriber.start

        end
      end
    end
  end
end
```
And I exec a rake command:
```
$ bundle exec rake run_worker

"Running worker"
E0121 21:39:49.713197000 140736594088896 backup_poller.cc:105]         run_poller: {"created":"@1516538389.713182000","description":"Shutting down timer system","file":"src/core/lib/iomgr/timer_generic.cc","file_line":630}
```
What is this error message??
I wanna use streaming subscriber.

**Comment by JoN1oP** [comment] 2018-01-22 12:16
Ruby: v2.4.3
google-cloud-pubsub: v0.29.0
Ubuntu 16.04

I had the same error message when trying to use `listen`. Couldn't find any relevant information as to what it means.

It's worth noting that `listen` will still work if you run your process as a daemon (infinite loop) but as soon as you exit the process, the error above will appear.

**Comment by mackeee-orange** [comment] 2018-01-23 17:12
@JoN1oP oh! It is true. I used that code with `timer` and `subscriber.stop.wait!`, that works correctly.
but when I execute that in `irb` , that works correctly too without `subscriber.stop.wait!` .  
  
hmm...  why that doesn't work on Rails??

**Comment by blowmage** [comment] 2018-01-23 17:43
What version of the `grpc` gem are you folks running?

**Comment by blowmage** [comment] 2018-01-23 18:03
@apolcyn Can you give us some insight into this GRPC message? It looks to me that this is printed during the process cleanup. Is that accurate? Is this an information message, a warning, or an error? Is there something the GRPC client can do to suppress this message?

FWIW, I can produce this message when opening read/write streams using grpc versions 1.8.0, 1.8.3, _and_ 1.9.0.pre1, but not 1.7.3 and earlier.

**Comment by blowmage** [comment] 2018-01-23 18:06
> why that doesn't work on Rails??

@mackeee-orange Can you elaborate on how this is not working with Rails? It appears to me to be a messages printed by the `grpc` gem, but I don't see any error being raised. AFAICT all processes are closing properly.

**Comment by mackeee-orange** [comment] 2018-01-23 18:45
@blowmage using `grpc (1.8.3 universal-darwin, 1.0.1 universal-darwin)`

When I execute `subscriber.start` without `subscriber.stop.wait!` on `irb` , streaming function work properly.
Off course, if I publish message, message is printed until put `Ctr-C`.
But on Rails, It doesn't seem to work without `stop.wait!`. After call function, the message appears immediately. => `E0121 21:39:49.713197000 140736594088896 backup_poller.cc:105]         run_poller: {"created":"@1516538389.713182000","description":"Shutting down timer system","file":"src/core/lib/iomgr/timer_generic.cc","file_line":630}`  
And then process close soon. I hope it become streaming process.

I suppose that closing is a specification, right?
I will solve this problem by using `stop.wait!` in `timer` .  
But if you have better solution, plz tell me.

**Comment by blowmage** [comment] 2018-01-23 19:46
@mackeee-orange Okay, so there is a lot here to unpack. A Pub/Sub Subscriber object is intended to belong to a long-running process where it can both receive and modify/acknowledge messages. To do this it opens an HTTP/2 stream using the `grpc` gem when calling `Subscriber#start` and closes it when calling `Subscriber#stop`. So calling `stop` immediately will not give the subscriber any time to do any work.

It appears that the message you are asking about is printed when the GRPC timer is cleaned up when the process exits. If you are seeing it immediately then its likely the process/thread is exiting immediately. The reason you don't see it in IRB when calling `stop` is that the IRB process hasn't ended yet. To illustrate this, here is an IRB session where I create a subscriber and the message prints on process exit:

```
$ bundle exec irb
irb(main):001:0> require "google/cloud/pubsub"
=> true
irb(main):002:0> p = Google::Cloud::Pubsub.new
=> #<Google::Cloud::Pubsub::Project:0x00007fdd44550c70 @service=Google::Cloud::Pubsub::Service(<my-project-id>)>
irb(main):003:0> t = p.create_topic "foo"
=> #<Google::Cloud::Pubsub::Topic:0x00007fdd445c2a00 @service=Google::Cloud::Pubsub::Service(<my-project-id>), @grpc=<Google::Pubsub::V1::Topic: name: "projects/<my-project-id>/topics/foo", labels: {}>, @lazy=nil, @exists=nil, @async_opts={}>
irb(main):004:0> s = t.subscribe "bar"
=> #<Google::Cloud::Pubsub::Subscription:0x00007fdd44673800 @service=Google::Cloud::Pubsub::Service(<my-project-id>), @grpc=<Google::Pubsub::V1::Subscription: name: "projects/<my-project-id>/subscriptions/bar", topic: "projects/<my-project-id>/topics/foo", push_config: <Google::Pubsub::V1::PushConfig: push_endpoint: "", attributes: {}>, ack_deadline_seconds: 10, retain_acked_messages: false, message_retention_duration: <Google::Protobuf::Duration: seconds: 604800, nanos: 0>, labels: {}>, @lazy=nil, @exists=nil>
irb(main):005:0> s2 = s.listen { |msg| puts msg.inspect }
=> #<Google::Cloud::Pubsub::Subscriber (subscription: projects/<my-project-id>/subscriptions/bar, streams: 4)>
irb(main):006:0> s2.start
=> #<Google::Cloud::Pubsub::Subscriber (subscription: projects/<my-project-id>/subscriptions/bar, streams: 4)>
irb(main):007:0> s2.stop.wait!
=> #<Google::Cloud::Pubsub::Subscriber (subscription: projects/<my-project-id>/subscriptions/bar, streams: 4)>
irb(main):008:0> exit
E0123 11:54:30.009503000 140736101983040 backup_poller.cc:108]         run_poller: {"created":"@1516733670.009485000","description":"Shutting down timer system","file":"src/core/lib/iomgr/timer_generic.cc","file_line":625}
$ 
```

I suspect the process used to call `listen` and use a subscriber object is exiting. But you have me at a disadvantage since I don't know what your `run_worker` rake task does. The simplest fix, however, is to block that process indefinitely by calling `sleep` after you start the subscriber. You may also consider referencing other libraries such as [activejob-google_cloud_pubsub](ursm/activejob-google_cloud_pubsub) as well.

**Comment by mackeee-orange** [comment] 2018-01-24 00:32
@blowmage Thank you for your polite explanation!
I will consider to use that libraries.

**Comment by apolcyn** [comment] 2018-01-24 03:46
@blowmage ack for your question above. It is indeed coming from shutdown though, and it would <i>seem</is> to indicate that something wasn't completely shut down. But still I'm not sure and this needs more investigation.

**Comment by apolcyn** [comment] 2018-01-24 06:10
@blowmage I'm seeing this error reproduce 100% under these somewhat-unique circumstances:
* an "operation view" of a new RPC is created by specifying `return_op: true` to the grpc stub
* that same RPC is also created with a deadline, e.g., `deadline: Time.now + 5`
* that RPC is never started or executed. (e.g., `<call>.execute` is never called)

For example, if I tweak the `main` method of [https://github.com/grpc/grpc/blob/master/examples/ruby/greeter_client.rb](greeter client) to:

```
  stub = Helloworld::Greeter::Stub.new('localhost:50051', :this_channel_is_insecure)
  user = ARGV.size > 0 ?  ARGV[0] : 'world'
 stub.say_hello(Helloworld::HelloRequest.new(name: user), return_op: true, deadline: Time.now + 5)
```

... then this error occurs 100% of the time. Is is possible that something along these lines is happening in the way that grpc is used here?

**Comment by blowmage** [comment] 2018-01-24 06:21
I see this message when running our acceptance tests, which definitely make the RPC calls.

**Comment by blowmage** [comment] 2018-01-24 06:26
Is it possible something in the GAPIC layer causes this?

**Comment by apolcyn** [comment] 2018-01-24 07:36
A search for `return_op` in (https://github.com/googleapis/gax-ruby)[the gax repo] turned up empty, which IIC is where the code that creates the stub here lives.

It's definitely possible that it has influence here... what I'm mostly wondering if if there's a situation where a grpc call is left anywhere in a "created but unfinished" state

**Comment by blowmage** [comment] 2018-01-24 19:47
If you look at the IRB example I posted above, or the acceptance tests, you will see that we do call the RPC endpoints. We see this message being printed in both pubsub and spanner when creating streams. Streaming RPC calls are mostly pass-through in regards to the GAPIC layer; it doesn't do any error handling or retry. Is it possible that something with how GAPIC is preparing the RPC calls is contributing?

/cc @geigerj

**Comment by blowmage** [comment] 2018-01-24 19:53
It definitely looks to happen when passing an `Enumerable` to a streaming RPC endpoint. Receiving an `Enumerable` from an RPC endpoint doesn't print the message.

**Comment by geigerj** [comment] 2018-01-24 20:37
GAPIC/GAX doesn't have any special code to trigger the gRPC "operation view", but it does allow you to pass arbitrary keyword args to the gRPC stub. To get the operation view, `return_op` would have to be set somewhere in the code calling GAPIC. It doesn't look like that's happening in google-cloud-ruby.

**Comment by apolcyn** [comment] 2018-01-24 23:13
@blowmage for your last comment:

> It definitely looks to happen when passing an Enumerable to a streaming RPC endpoint. Receiving an Enumerable from an RPC endpoint doesn't print the message.

Do you know which types of RPC's are getting called here? e.g., bidirectional-streaming, streaming-from-client-to-server, or streaming-for-server-to-client?

That is, have you noticed the error when passing an `Enumerable` to the bidi-streaming RPC endpoint and ignoring the response? Or  have you noticed the error when passing an `Enumerable` to a streaming-from-client-to-server RPC endpoint?

**Comment by blowmage** [comment] 2018-01-24 23:29
> Do you know which types of RPC's are getting called here? e.g., bidirectional-streaming, streaming-from-client-to-server, or streaming-for-server-to-client?

Bidirectional. We don't access any endpoints where we only upload. We do hit some endpoints where we only download, but those don't print the message.

**Comment by apolcyn** [comment] 2018-01-25 02:19
Ok, I believe that I am also reproducing the originally posted error by using the pubsub API directly, with this repro script:

```
p = Google::Cloud::Pubsub.new
t = p.topic TOPIC
s = t.subscription SUBSCRIPTION
subscriber = s.listen threads: { callback: 16 } do |message|
  p message
  message.acknowledge!
end

subscriber.start
```

Running that under `GRPC_VERBOSITY=DEBUG` env var shows this output:

```
I0125 01:59:45.407843267   19772 ev_epoll1_linux.cc:95]      grpc epoll fd: 7
D0125 01:59:45.407890347   19772 ev_posix.cc:131]            Using polling engine: epoll1
D0125 01:59:45.407962122   19772 dns_resolver.cc:307]        Using native dns resolver
D0125 01:59:45.408689270   19781 rb_channel.c:681]           GRPC_RUBY: run_poll_channels_loop - create connection polling thread
D0125 01:59:45.408727326   19781 rb_channel.c:605]           GRPC_RUBY: run_poll_channels_loop_no_gil - begin
D0125 01:59:45.408854654   19772 rb_channel.c:691]           GRPC_RUBY: wait for channel polling thread to start
D0125 01:59:45.506414321   19772 rb_channel.c:691]           GRPC_RUBY: wait for channel polling thread to start
D0125 01:59:45.656154672   19772 rb_channel.c:649]           GRPC_RUBY: run_poll_channels_loop_unblocking_func - begin aborting connection polling
D0125 01:59:45.657311932   19772 rb_channel.c:672]           GRPC_RUBY: run_poll_channels_loop_unblocking_func - end aborting connection polling
D0125 01:59:45.657372366   19781 rb_channel.c:637]           GRPC_RUBY: run_poll_channels_loop_no_gil - exit connection polling loop
E0125 01:59:45.682649230   19772 backup_poller.cc:105]       run_poller: {"created":"@1516845585.682626133","description":"Shutting down timer system","file":"src/core/lib/iomgr/timer_generic.cc","file_line":630}
D0125 01:59:46.684319272   19772 iomgr.cc:95]                Waiting for 1 iomgr objects to be destroyed
D0125 01:59:47.686032536   19772 iomgr.cc:95]                Waiting for 1 iomgr objects to be destroyed
D0125 01:59:48.687788986   19772 iomgr.cc:95]                Waiting for 1 iomgr objects to be destroyed
D0125 01:59:49.689685071   19772 iomgr.cc:95]                Waiting for 1 iomgr objects to be destroyed
D0125 01:59:50.691612001   19772 iomgr.cc:95]                Waiting for 1 iomgr objects to be destroyed
D0125 01:59:51.693372365   19772 iomgr.cc:95]                Waiting for 1 iomgr objects to be destroyed
D0125 01:59:52.695359116   19772 iomgr.cc:95]                Waiting for 1 iomgr objects to be destroyed
D0125 01:59:53.698180892   19772 iomgr.cc:95]                Waiting for 1 iomgr objects to be destroyed
D0125 01:59:54.699966364   19772 iomgr.cc:95]                Waiting for 1 iomgr objects to be destroyed
D0125 01:59:55.701737130   19772 iomgr.cc:125]               Failed to free 1 iomgr objects before shutdown deadline: memory leaks are likely
D0125 01:59:55.701794725   19772 iomgr.cc:75]                LEAKED OBJECT: tcp-client:ipv4:209.85.145.95:443 fd=10 0x7f0ea0003288
D0125 01:59:55.701898303   19772 metadata.cc:133]            WARNING: 1 metadata elements were leaked
D0125 01:59:55.701920741   19772 metadata.cc:133]            WARNING: 1 metadata elements were leaked
D0125 01:59:55.701929109   19772 metadata.cc:133]            WARNING: 1 metadata elements were leaked
D0125 01:59:55.701945604   19772 slice_intern.cc:318]        WARNING: 1 metadata strings were leaked
D0125 01:59:55.701955551   19772 slice_intern.cc:325]        LEAKED: 61 74 74 61 63 68 6d 65 6e 74 'attachment'
D0125 01:59:55.701964044   19772 slice_intern.cc:318]        WARNING: 1 metadata strings were leaked
D0125 01:59:55.701972779   19772 slice_intern.cc:325]        LEAKED: 70 75 62 73 75 62 2e 67 6f 6f 67 6c 65 61 70 69 73 2e 63 6f 6d 'pubsub.googleapis.com'
D0125 01:59:55.701985141   19772 slice_intern.cc:318]        WARNING: 1 metadata strings were leaked
D0125 01:59:55.701998037   19772 slice_intern.cc:325]        LEAKED: 67 72 70 63 2d 63 2f 35 2e 30 2e 30 20 28 6c 69 6e 75 78 3b 20 63 68 74 74 70 32 3b 20 67 65 6e 65 72 6f 75 73 29 'grpc-c/5.0.0 (linux; chttp2; generous)'
```


That exact same log can be reproduced by tweaking [this grpc test that uses bidi streaming](https://github.com/grpc/grpc/blob/master/src/ruby/spec/client_auth_spec.rb#L133) to this:

```
  class SleepingEnum
    def initialize(s)
      @s = s
    end
    def each
      @s.each do |r|
        yield r
        sleep 1
      end
    end
  end

  it 'client-server auth with bidi RPCs' do
    rs = SleepingEnum.new([EchoMsg.new, EchoMsg.new])
    t = Thread.new { @stub.a_bidi_rpc(rs).each { |r| p r } }
    sleep 1
    t.kill
  end
```

where in particular it kills a thread that's carrying out a grpc call. 

Is it possible that something like this is going on here? If it is actually the case, then I think this error represents a real but benign application shutdown issue...

**Comment by blowmage** [comment] 2018-01-25 15:30
Our situation is a bit different than your test code. We call the RPC on the main thread, but iterate the returned Enumerable on a child thread.

```ruby
  it 'client-server auth with bidi RPCs' do
    rs = SleepingEnum.new([EchoMsg.new, EchoMsg.new])
    enum = @stub.a_bidi_rpc(rs)
    t = Thread.new { enum.each { |r| p r } }
    sleep 1
    t.kill
  end
```

When a Pub/Sub Subscriber object is stopped, we have many of these child threads that are killed. Because of the coarseness of using Enumerable to represent the streaming requests and responses, we can't apply back-pressure on the service, so we could have hundreds of messages that are left on the response Enumerable object or queued in the GRPC client. Killing the thread is the cleanest way to stop the process and start the cleanup process to make sure that the messages that have been pulled from the Enumerable are processed to completion.

This messages started since grpc version 1.8.0. Did something change in 1.8.0 to start this?

**Comment by blowmage** [comment] 2018-01-25 17:13
I can also reproduce this message in google-cloud-spanner, which only uses response Enumerable objects and doesn't use threads. But the repro is not clean and is too complex to share here.

**Comment by apolcyn** [comment] 2018-01-25 18:59
Thanks for info. Note that threads could still potentially be ending abruptly when the spanner API is used because a grpc-ruby bidi stream spawns it's own [background thread](https://github.com/grpc/grpc/blob/master/src/ruby/lib/grpc/generic/bidi_call.rb#L74).

Anyways seeing that this can be caused by unclean <i>process shut down</i>, I think we might be able to relax the verbosity of that error within grpc, seeing that the error here should be benign - https://github.com/grpc/grpc/pull/14180.

FYI, note that a different solution is you also might be able to `cancel` an inflight gRPC call by using the `operation` view of a grpc call (specifying `return_op: true`), and then calling `cancel` on the operation object.

**Comment by blowmage** [comment] 2018-01-25 19:14
We don’t want to close the GRPC stream, we want to stop getting responses while we process all previously received responses. Once all the previous responses are processed and subsequent requests are made (they have to be made on the same stream) then we can close the stream. We need to keep the upstream connection open.

**Closed** 2018-01-31 00:27 UTC
Labels: api: pubsub, type: question

**Comment by BenBach** [comment] 2018-02-06 15:18
@blowmage What is the recommend way to keep the connection open on an heroku worker?

**Comment by blowmage** [comment] 2018-02-06 15:48
I am not familiar with Heroku workers. I'd suggest asking this on StackOverflow.
