### ISSUE TITLE
Mysterious Pub/Sub timeouts if using any version past 0.6.3

### ISSUE THREAD

**Issue by Hopperman** [GoogleCloudPlatform/google-cloud-ruby#825] opened 2016-08-11 16:01 UTC
For some odd reason if I try and upgrade the gem version past 0.6.3 Gcloud pubsub stops working.

`gcloud = Gcloud.new('my_project_id', 'my_key')`
`pubsub = gcloud.pubsub`
works up until here:
`pubsub.topic = "my_topic"`

Just runs endlessly...  Any ideas on how I can better debug or figure out what's wrong?

I've tried 0.12.2 and 0.11.0

**Comment by quartzmo** [comment] 2016-08-12 17:05
@Hopperman Thanks for opening this issue! I tried to reproduce it myself using `0.12.2`. This is what I get:

```sh
irb(main):001:0> pubsub = gcloud.pubsub
D0812 11:02:46.268869000 140735211810816 ev_posix.c:106] Using polling engine: poll
=> #<Gcloud::Pubsub::Project:0x007f98a416d368 @service=Gcloud::Pubsub::Service(bustling-kayak-91516)>
irb(main):002:0> pubsub.topic = "my_topic"
NoMethodError: undefined method `topic=' for #<Gcloud::Pubsub::Project:0x007f98a416d368>
	from (irb):2
```

Are you sure about the code you pasted in your description?

**Comment by Hopperman** [comment] 2016-08-12 18:15
@quartzmo No worries! thought it might be helpful to others who stumble upon the same issue

Pretty sure. I'll attach a screenshot from my terminal soon

**Comment by quartzmo** [comment] 2016-08-12 23:19
@Hopperman The method invoked in your code does not exist, either in the current version (`0.12.x`) or in earlier versions such as `0.6.x`. Can you try some other logic to test your upgrade?

**Comment by Hopperman** [comment] 2016-08-12 23:24
@quartzmo This is using the old version in my rails console
`rails c
Running via Spring preloader in process 57909
Loading development environment (Rails 5.0.0.rc1)
irb: warn: can't alias context from irb_context.
irb(main):001:0> Gcloud.new('comship-1198', File.open('./cs-pubsub-develop.json'))
=> #<Object:0x007f9eb927a510 @project="comship-1198", @keyfile=#<File:./cs-pubsub-develop.json>>
irb(main):002:0> gc = _
=> #<Object:0x007f9eb927a510 @project="my-project", @keyfile=#<File:./cs-pubsub-develop.json>>
irb(main):003:0> gc.pubsub
=> #<Gcloud::Pubsub::Project:0x007f9eb9232558 @connection=Gcloud::Pubsub::Connection(comship-1198)>
irb(main):004:0> pubsub = _
=> #<Gcloud::Pubsub::Project:0x007f9eb9232558 @connection=Gcloud::Pubsub::Connection(my-project)>
irb(main):006:0> pubsub.create_topic "new-topic"
=> #<Gcloud::Pubsub::Topic:0x007f9eb860bc70 @connection=Gcloud::Pubsub::Connection(comship-1198), @gapi=#<Google::APIClient::Schema::Pubsub::V1::Topic:0x3fcf5c305f00 DATA:{"name"=>"projects/my-project/topics/new-topic"}>, @name=nil, @exists=nil>`

**Comment by Hopperman** [comment] 2016-08-12 23:30
Also wow that's weird because after I call pubsub.create_topic I can do this: 

`irb(main):007:0> pubsub.topic "my-topic"
=> #<Gcloud::Pubsub::Topic:0x007f9eb85b9c40 @connection=Gcloud::Pubsub::Connection(comship-1198), @gapi=#<Google::APIClient::Schema::Pubsub::V1::Topic:0x3fcf5c2dced4 DATA:{"name"=>"projects/my-project/topics/my-topic"}>, @name=nil, @exists=nil>`

**Comment by quartzmo** [comment] 2016-08-12 23:31
In the description for this issue (above), you wrote:

```ruby
pubsub.topic = "my_topic"
```

not



```ruby
pubsub.topic "my_topic"
```

**Comment by quartzmo** [comment] 2016-08-12 23:34
I can't reproduce any issue in `0.12.2`, it all works fine for me.

**Comment by Hopperman** [comment] 2016-08-12 23:35
My apologies, that must have been a typo. 

Must be something wrong with my local environment then, will try a complete fresh install on a VM or different machine. Thanks for looking into this.

**Comment by quartzmo** [comment] 2016-08-12 23:54
Sounds good! If you don't find anything can you please close this issue? Cheers!

**Comment by quartzmo** [comment] 2016-08-13 17:18
When you do your fresh install, you might want to look for anything amiss with the installation of the `grpc` dependency. In all versions `0.7.0` and later, the Pub/Sub support uses gRPC for its transport layer.

**Comment by Hopperman** [comment] 2016-08-13 18:13
Will do, I think it might actually be grpc somehow. Will close once I've confirmed

**Closed** 2016-09-06 14:21 UTC
Labels: pubsub

**Comment by blowmage** [comment] 2016-09-06 15:45
@Hopperman Did you find the problem?

**Comment by Hopperman** [comment] 2016-09-06 15:49
@blowmage  Yep, I started seeing gRPC errors. Not sure why yet but I'm guessing it's my environment. Will reopen another, more specific, ticket if I can't manage to fix it.

**Comment by blowmage** [comment] 2016-09-06 15:51
@Hopperman More info would be terrific. Let me know if you want to remote pair on it.

**Comment by Hopperman** [comment] 2016-09-06 15:54
@blowmage thanks! that would be amazing. Will keep you posted, busy implementing pubsub (again) in another service where I'll be using the latest versions. So I'm pretty sure I'll run into it soon.
